### PR TITLE
Add ServerGears initial UI

### PR DESCRIPTION
**Pull request by PedroHLC**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/355)

### CODE REVIEW

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[webpack.config.js, line 89 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26vBc5cVAcv9ef5MgH:-L26vBc5cVAcv9ef5MgI:bb7qx3u) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/webpack.config.js#L89)):*
> ```JavaScript
>         to: 'favicon.ico'
>       },
>     ]),
> ```

wat?

---

*[src/Apps/ServersGears/Models.elm, line 21 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26qygU3fOdBMnJVA9x:-L26qygU3fOdBMnJVA9y:b-jvjump) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Models.elm#L21)):*
> ```Elm
>     , selection : Maybe Selection
>     , motherboard : Maybe Motherboard
>     , anyChange : Bool
> ```

Avoiding useless diff calls? :stuck_out_tongue: 

---

*[src/Apps/ServersGears/Models.elm, line 175 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rHOoxKzw6YynhVxA:-L26rHOoxKzw6YynhVxB:b-tj9vlv) ([raw file](https://github.com/hackerexperience/heborn/blob/89df7006cb92a28a28860b6ddc4d3805e6147ad4/src/Apps/ServersGears/Models.elm#L175)):*
> ```Elm
>             removeSelection model
> ```

idk what happened here, hope it looks gud

---

*[src/Apps/ServersGears/Models.elm, line 199 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rlclDAZ0eA8PfGFt:-L26rlclDAZ0eA8PfGFu:bz5z98t) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Models.elm#L199)):*
> ```Elm
>                             (Inventory.Component idA)
>                             inventory
>                             motherboard
> ```

renato didn't wanted this feature, but I'm cool with it

---

*[src/Apps/ServersGears/Models.elm, line 202 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rfxqkNCUW9xE0kav:-L26rfxqkNCUW9xE0kaw:b-mp6850) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Models.elm#L202)):*
> ```Elm
> 
>                 Nothing ->
>                     setSelection (Just <| SelectingSlot slotIdB) model
> ```

yup. solved that selection problem

---

*[src/Apps/ServersGears/Models.elm, line 263 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rupeNuGtOot-ANif:-L26rupeNuGtOot-ANig:b-wv18mu) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Models.elm#L263)):*
> ```Elm
>                 |> removeSelection
>         else
>             setSelection (Just <| SelectingSlot slotId) model
> ```

So you moved most of the complexity here, not sure if I like it, the previous solution had smaller functions, but this one isn't that bad (my first version of the previous solution was way messier)

---

*[src/Apps/ServersGears/Models.elm, line 402 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rP3YA43I9yaEZzw_:-L26rP3YA43I9yaEZzwa:bg25kzw) ([raw file](https://github.com/hackerexperience/heborn/blob/89df7006cb92a28a28860b6ddc4d3805e6147ad4/src/Apps/ServersGears/Models.elm#L402)):*
> ```Elm
> -- internals - doSelect helpers
> ```

idk what you rolled out to get ridden of this amount of code, but congrats

---

*[src/Apps/ServersGears/Update.elm, line 139 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26sMLzXyYU73BFT7qH:-L26sMLzXyYU73BFT7qI:b9yf0n1) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Update.elm#L139)):*
> ```Elm
>             _ ->
>                 Update.fromModel <|
>                     { model | selection = selection_ }
> ```

hmm, moving the selection logic here, ok, cool

---

*[src/UI/Widgets/Motherboard.elm, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26ufxGVraavYIsQBXs:-L26ufxGVraavYIsQBXt:bes79vo) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/UI/Widgets/Motherboard.elm#L12)):*
> ```Elm
> 
> defaultMobo : (Motherboard.SlotId -> msg) -> Motherboard -> Html msg
> defaultMobo select { slots } =
> ```

Tip: pattern match the Motherboard record to find what motherboard you're handling, use this data to delegate drawing the motherboard to another function, each motherboard will have its own rendering function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-:-L26v9N4edIqQNMhJkKP:bnfp4nl)*

**Comment by PedroHLC** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Apps/ServersGears/Models.elm, line 21 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26qygU3fOdBMnJVA9x:-L2LUvW699cJOjsRl30Z:b-ecx6yj) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/Apps/ServersGears/Models.elm#L21)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Avoiding useless diff calls? :stuck_out_tongue: 
</blockquote></details>

Actually, it's better in visual feedback

---

*[src/UI/Widgets/Motherboard.elm, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26ufxGVraavYIsQBXs:-L2Lcz--W-Ob2PzpL6EH:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/632104f392224620e9d86e3cc3813c0d68a47d9e/src/UI/Widgets/Motherboard.elm#L12)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Tip: pattern match the Motherboard record to find what motherboard you're handling, use this data to delegate drawing the motherboard to another function, each motherboard will have its own rendering function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/355)*

**Comment by themaxhero** [comment]
Reviewed 14 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Apps/ServersGears/Models.elm, line 175 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-L26rHOoxKzw6YynhVxA:-L2LeabldF1TDhKqX-sJ:b-2guby3) ([raw file](https://github.com/hackerexperience/heborn/blob/89df7006cb92a28a28860b6ddc4d3805e6147ad4/src/Apps/ServersGears/Models.elm#L175)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

idk what happened here, hope it looks gud
</blockquote></details>

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/355)*

**Comment by themaxhero** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/355#-:-L2Lg_UZtaisy6gZd-rW:bnfp4nl)*

**Pull request merged**
