### PR TITLE
Network Selector

### PR DESCRIPTION
**Pull request by PedroHLC**
This commit will allow players to choose a target local network!

Bonus:
* Preciser TaskManager ETA

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/332)

### CODE REVIEW

**Comment by renatomassaro** [comment]
"work" in progress :rofl:

**Comment by PedroHLC** [comment]
It's worse than it looks! I don't remember even what I have to do now! Have to improvise some replanning....

**Comment by PedroHLC** [comment]
* NetworkSwitcher
  * [ ] Show active
  * [ ] List others available ones form Servers' NIPs
  * [ ] Hide when there only the active one
  * [ ] Do the dropdown thing work as a dropdown thing
  * [ ] Select new active
* BounceManager (Two Stack Collumns)
  * [ ] List available addresses on the left
  * [ ] List selected addresses on the right
  * [ ] Click on one to the left to push it to the right
  * [ ] Click on one to the right to pop it back to where it came from
  * [ ] List available bounces
  * [ ] Add edit button
  * [ ] Add "new" button
  * [ ] Put buttons to work
* Implicit bounces (optmist like)
  !!! I DON'T REMEMBER WHAT IS THIS ANYMORE, I SUMMON @kress95 TO HELP ME FIGURE WHAT I WANTED TO DO !!!
* Bounce data request
  * Ask Renato to Add Backend stuff
     * Bootstrap bounce intel!
     * Change/Add bounces requests!

**Comment by kress95** [comment]
I'm reviewing this, but I'm not sure about the package.json part, is it being tested on jenkins? I'll skip it.

---

Reviewed 23 of 23 files at r1, 3 of 7 files at r2, 21 of 24 files at r3.
Review status: 36 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[package.json, line 6 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-L0MIf3fPz-4x1LaRNpT:-L0MIf3fPz-4x1LaRNpU:b5p10rh) ([raw file](https://github.com/hackerexperience/heborn/blob/5f394534c5e5ad3753bec16c86c2523c27352b0d/package.json#L6)):*
> ```JSON
>   "version": "0.8.4",
>   "license": "MIT",
>   "author": "Peter Morawiec",
> ```

wat the actual eff

---

*[src/Game/Models.elm, line 154 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-L0MLl_8HIIAugDj2LRv:-L0MLl_8HIIAugDj2LRw:bb76hiy) ([raw file](https://github.com/hackerexperience/heborn/blob/7565a862887572003675bf83c473cce95b462206/src/Game/Models.elm#L154)):*
> ```Elm
> 
>         Nothing ->
>             "Player has no active gateway! [2]"
> ```

Wat?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-:-L-IYAdDpKSOA00GB0UA:b-iqbf98)*

**Comment by kress95** [comment]
Reviewed 1 of 7 files at r2, 2 of 24 files at r3, 46 of 46 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-L1xZA6Rn-5Q-CjLFH_w:-L1xZA6Rn-5Q-CjLFH_x:b-j4wzr5) ([raw file](https://github.com/hackerexperience/heborn/blob/7565a862887572003675bf83c473cce95b462206/package.json#L14)):*
> ```JSON
>     "copy-webpack-plugin": "^4.2.3",
>     "css-loader": "^0.28.7",
>     "elm": "^0.18.0",
> ```

using global elm? wat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/332)*

**Comment by PedroHLC** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[package.json, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-L1xZA6Rn-5Q-CjLFH_w:-L20c51xl88AxQSGr-IG:bkm94jt) ([raw file](https://github.com/hackerexperience/heborn/blob/7565a862887572003675bf83c473cce95b462206/package.json#L14)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

using global elm? wat
</blockquote></details>

Just for ensuring version, elm will always be installed as an elm-format dependency.
If you don't wanna use it, you can always run ```make prefer-native```

---

*[src/Game/Models.elm, line 154 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/332#-L0MLl_8HIIAugDj2LRv:-L20caATyFAUJEHAAZd3:btvnej9) ([raw file](https://github.com/hackerexperience/heborn/blob/7565a862887572003675bf83c473cce95b462206/src/Game/Models.elm#L154)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Wat?
</blockquote></details>

That was required as we have two places that throw the same error with the same description...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/332)*

**Pull request merged**
