### PR TITLE
Solves #43, #62, #23

### PR DESCRIPTION
**Pull request by PedroHLC**
Depends on: Nothing

---

Issues #43, #62 and #23 solved.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/82)

### CODE REVIEW

**Comment by kress95** [comment]
*[src/Apps/LogViewer/View.elm, line 86 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOqTzHLsFIhQ6LM-0t:-KjOqTzHLsFIhQ6LM-0u:b-70sax8) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/Apps/LogViewer/View.elm#L86)):*
> ```Elm
> renderButtons : List Classes -> List (Html Msg)
> renderButtons btns =
>     case List.tail (List.concat (List.map (\d -> [ text " ", span [ class [ d ] ] [] ]) btns)) of
> ```

```elm
btns
|> List.map (\d -> [ text " ", span [ class [ d ] ] [] ]) 
|> List.concat
|> List.tail
|> Maybe.withDefault []
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82)*

**Comment by kress95** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOvhLD2M-PdZQHhH8M:-KjOvhLD2M-PdZQHhH8N:b-nnlyvn) (no related file):*
The code is okay (considering our data modeling), my comments are change suggestions, not change requests.

> Of course we could improve our data model to make this less messy, but it would require tons of changes, there's not much we could do about it now.

---

*[src/Apps/Explorer/View.elm, line 262 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOtR_XoKu86ZE0AP3W:-KjOtR_Y3qyKd_57RFdu:b8ys1mr) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/Apps/Explorer/View.elm#L262)):*
> ```Elm
>                                         actions
>                                     )
>                                 ]
> ```

this is okay (albeit hard to read), I believe this is more readable:

```elm
let
    type_ =
        (Executable exeMime ver Nothing)

    archive =
        Archive { prop | type_ = type_ }

    entry_ =
        { entry | type_ = archive }
in
    div [ class [ CntListContainer ] ]
        [ (renderDetailedEntry entry_)
        , div [ class [ CntListChilds ] ]
            (renderActionList actions)
        ]
```

I know you hate to use let on FP cause it reminds you about imperative code, but it's really not imperative, every "variable" defined on let is constant, it won't hurt your code purity.

A functional let is just an optimized sugar for that:

```elm
(\type_ ->
    (\archive ->
        (\ entry_ ->
            div [ class [ CntListContainer ] ]
                [ (renderDetailedEntry entry_)
                , div [ class [ CntListChilds ] ]
                    (renderActionList actions)
                ]
        ) ({ entry | type_ = archive })
    ) (Archive { prop | type_ = type_ })
) (Executable exeMime ver Nothing)
```

(yeah, this is one of the few things that elm compiler is able to optimize, 'cause it doesn't depend on type information)

Lambda calculus is all about things looking like that, you should not fear it.

---

*[src/OS/Dock/Models.elm, line 88 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOv1UfwGrNhqRF5ZYw:-KjOv1UgK02bk12K7-lM:bokgouu) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/OS/Dock/Models.elm#L88)):*
> ```Elm
> updateInstances : Model -> Windows -> Model
> updateInstances model windows =
>     { model | dock = (List.map (\app -> (refreshInstances windows app)) model.dock) }
> ```

I know this is not a change, but this code would work the same:

```elm
{ model | dock = List.map (refreshInstances windows) model.dock }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/Explorer/View.elm, line 262 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOtR_XoKu86ZE0AP3W:-KjOx1ur_qbk6dXsOwkB:bap7hr7) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/Apps/Explorer/View.elm#L262)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

this is okay (albeit hard to read), I believe this is more readable:

```elm
let
    type_ =
        (Executable exeMime ver Nothing)

    archive =
        Archive { prop | type_ = type_ }

    entry_ =
        { entry | type_ = archive }
in
    div [ class [ CntListContainer ] ]
        [ (renderDetailedEntry entry_)
        , div [ class [ CntListChilds ] ]
            (renderActionList actions)
        ]
```

I know you hate to use let on FP cause it reminds you about imperative code, but it's really not imperative, every "variable" defined on let is constant, it won't hurt your code purity.

A functional let is just an optimized sugar for that:

```elm
(\type_ ->
    (\archive ->
        (\ entry_ ->
            div [ class [ CntListContainer ] ]
                [ (renderDetailedEntry entry_)
                , div [ class [ CntListChilds ] ]
                    (renderActionList actions)
                ]
        ) ({ entry | type_ = archive })
    ) (Archive { prop | type_ = type_ })
) (Executable exeMime ver Nothing)
```

(yeah, this is one of the few things that elm compiler is able to optimize, 'cause it doesn't depend on type information)

Lambda calculus is all about things looking like that, you should not fear it.
</blockquote></details>

I see, this was not a change, my bad, but it's your code, do not feel any urge to update it, just take it as a lesson on how lambda/fp works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82)*

**Comment by kress95** [comment]
This looks like a WIP commit, as it looks like we can't restore individual windows yet, you could add a [WIP] tag to the title and a TODO list to PR body :yum:

The way you moved this to revision made it looks like a pre-merge revision request. :upside_down_face:

**Comment by PedroHLC** [comment]
Review status: 3 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/Apps/Explorer/View.elm, line 262 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOtR_XoKu86ZE0AP3W:-KjYWSZSXG8js8d9l5OH:bf660tj) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/Apps/Explorer/View.elm#L262)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I see, this was not a change, my bad, but it's your code, do not feel any urge to update it, just take it as a lesson on how lambda/fp works.
</blockquote></details>

Yeah, much more readable! :smile: 

---

*[src/OS/Dock/Models.elm, line 88 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjOv1UfwGrNhqRF5ZYw:-KjYWeuvv-lbBpF37_n8:b-wieem) ([raw file](https://github.com/hackerexperience/heborn/blob/e02d2c4dc7024d577e512f31e6f236eaf45abce7/src/OS/Dock/Models.elm#L88)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I know this is not a change, but this code would work the same:

```elm
{ model | dock = List.map (refreshInstances windows) model.dock }
```
</blockquote></details>

Forgot elm functions allowed this. Done :smiley: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82)*

**Comment by kress95** [comment]
Does this PR depends on anything?
Please enumerate PR's dependencies so Renato is able to sort which PR to review before others.

**Comment by kress95** [comment]
> By accident, one can switch renderTreeEntryList and renderDetailedEntryList to change viewing style...
> (I didn't planned it that way)

This happens a lot with functional programming :stuck_out_tongue:

**Comment by kress95** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/OS/WindowManager/Update.elm, line 62 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjoRPueKI8GDGplnlmg:-KjoRPueKI8GDGplnlmh:b-4gzlud) ([raw file](https://github.com/hackerexperience/heborn/blob/7334124ed8658c63e674e56d0b277e129097b234/src/OS/WindowManager/Update.elm#L62)):*
> ```Elm
>                         { model
>                             | windows = windows_
>                         }
> ```

I would do it on a single line, but whatever

```elm
{ model | windows = windows_ }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82)*

**Comment by kress95** [comment]
> Does this PR depends on anything?
> Please enumerate PR's dependencies so Renato is able to sort which PR to review before others.

Just asked and it depends on "Nothing" :stuck_out_tongue:

**Comment by renatomassaro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/OS/WindowManager/Update.elm, line 62 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KjoRPueKI8GDGplnlmg:-KkIvd4drG9cXLFCeJsh:br34q3q) ([raw file](https://github.com/hackerexperience/heborn/blob/7334124ed8658c63e674e56d0b277e129097b234/src/OS/WindowManager/Update.elm#L62)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I would do it on a single line, but whatever

```elm
{ model | windows = windows_ }
```
</blockquote></details>

This should be a single line, yes. I'll merge anyway, we can fix it later.

---

*[src/OS/WindowManager/Update.elm, line 68 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-KkIvmqyvtbwtspA6MtB:-KkIvmqyvtbwtspA6MtC:begao4i) ([raw file](https://github.com/hackerexperience/heborn/blob/7334124ed8658c63e674e56d0b277e129097b234/src/OS/WindowManager/Update.elm#L68)):*
> ```Elm
>                     [ callDock (DockMsg.WindowsChanges windows_) ]
>             in
>                 ( model_
> ```

Also one line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/82#-:-KkIw1Kw5OTqU-ds_VtC:bnfp4nl)*

**Pull request merged**
