### PR TITLE
Add LogViewer menu entries

### PR DESCRIPTION
**Pull request by themaxhero**
Added the following menu entries on LogViewer:

- Encrypt
- Decrypt
- Delete
- Hide

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/307)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Reviewed 2 of 6 files at r1, 3 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[package.json, line 57 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZIuQrrWaWYmvOTit:-KxrZIuQrrWaWYmvOTiu:bdulejc) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/package.json#L57)):*
> ```JSON
>     "webpack-dev-server": "^1.16.3"
>   }
> }
> ```

REVERT this changes

---

*[src/Apps/LogViewer/Menu/Actions.elm, line 73 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrYz--ocIsIEn5uDaB:-KxrYz--ocIsIEn5uDaC:booq49w) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/src/Apps/LogViewer/Menu/Actions.elm#L73)):*
> ```Elm
>                 ( model, Cmd.none, dispatch )
> 
>         EntryHide logId ->
> ```

These actions should also occur "ahead of the game dispatch", in better words, besides dispatching to game, you have to change the model

---

*[src/Apps/LogViewer/Menu/View.elm, line 57 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZ_8NujipQlnzuIpB:-KxrZ_8NujipQlnzuIpC:bo94skk) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/src/Apps/LogViewer/Menu/View.elm#L57)):*
> ```Elm
>             ]
> 
>         MenuEncryptEntry logID ->
> ```

MenuEncrypt**ed**Entry would be a better name, as its describing the entry state and not the encryption action....

---

*[src/Apps/LogViewer/Menu/View.elm, line 83 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZr0Yo_Fvf6c01rIE:-KxrZr0Yo_Fvf6c01rIF:b-2r2yib) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/src/Apps/LogViewer/Menu/View.elm#L83)):*
> ```Elm
> 
> menuEncryptEntry : Logs.ID -> Html.Attribute LogViewer.Msg
> menuEncryptEntry logID =
> ```

This function name, should be `menuEncryptedEntry`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/307)*

**Comment by themaxhero** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/LogViewer/Menu/View.elm, line 57 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZ_8NujipQlnzuIpB:-KxwxvaCIIIexiXB88-4:b-886gsx) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/src/Apps/LogViewer/Menu/View.elm#L57)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

MenuEncrypt**ed**Entry would be a better name, as its describing the entry state and not the encryption action....
</blockquote></details>

Fixed

---

*[src/Apps/LogViewer/Menu/View.elm, line 83 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZr0Yo_Fvf6c01rIE:-KxwxjXHxHB-X37my88O:b-886gsx) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/src/Apps/LogViewer/Menu/View.elm#L83)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

This function name, should be `menuEncryptedEntry`
</blockquote></details>

Fixed

---

*[package.json, line 57 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-KxrZIuQrrWaWYmvOTit:-Kxwxs8wH-N1_R19z_eb:bwvyox4) ([raw file](https://github.com/hackerexperience/heborn/blob/84017085157093ae2597cd29107c42dcc101bbee/package.json#L57)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

REVERT this changes
</blockquote></details>

Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/307)*

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/307#-:-Kxwzg3qCuVcCrlx5hDt:bnfp4nl)*

**Comment by PedroHLC** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/307)*

**Pull request merged**
