### PR TITLE
Flexible Setup Pages

### PR DESCRIPTION
**Pull request by kress95**
### DONE

- [x] Update decoders to include setup page lists
- [x] Mainframe (done in another PR)
- [x] Create extra client-only pages
- [x] Added hostname setup
- [x] Rewrite  Setup.Model / Setup.View / Setup.Update / Setup.Subscriptions
- [x] Write a Pages mechanism for Setup
- [x] Move old  Setup.Model / Setup.View / Setup.Update / Setup.Subscriptions code to pages
- [x] Create requests
  - [x] `account.setup`
  - [x] `server.name.check`
  - [x] `server.name.set`
  - [x] `server.location.check`
  - [x] `server.location.set`
- [x] Goto previous page

### Unplanned Tasks

- [x] Rename `Step => Page`
- [x] Loading state
- [x] Removed an hardcoded bool from Core.Boot, that forced going into Setup every time.
- [x] Forcing going to Setup every time, it'll contain a loading spinner and won't show up unless player the has something to setup.
- [x] Update Setup code to work with Page lists.
- [x] Rebased with master 0b1e0df
- [x] Remove delay code
- [x] Weird map bug I don't know how to fix (@PedroHLC gibe help pls)

### Dev Log

- `Day 1`: not much done here, had to help with other things and we had some meetings;
- `Day 2`: worked half/day on it (cause meetings and help with production bugs);
- `Day 3`: worked whole day on it, wrote a lot of code as you can see on 20/Oct commits;
- `Day 4`: worked half/day on it, had some meetings and discussions taking time;
- `Day 5`: fixed remaining problems, probably 1h only

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/294)

### CODE REVIEW

**Comment by kress95** [comment]
Who would know this PR would take more than 1kloc of changes and touch +36 files?!

And it's isnt't even ready yet.
Now I understand why this is taking so long to finish...

My main problems now are: 

- Finishing requests
- Understanding/fixing the map bug, I'm requesting help from @PedroHLC for that

**Comment by kress95** [comment]
Still needing help to fix the map bug.
I'm also needing help, I need a better place for [this folder](https://github.com/kress95/HEBorn/tree/07223243c43ea3436ae8609717d29b53de1b1ee0/src/Game/Servers/Settings)

**Comment by kress95** [comment]
Even if the [folder](https://github.com/kress95/HEBorn/tree/07223243c43ea3436ae8609717d29b53de1b1ee0/src/Game/Servers/Settings) is okay, do not merge this until we get production support.

It's impossible to leave Setup without proper server name set support.

**Comment by PedroHLC** [comment]
Reviewed 3 of 35 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/294)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Core/Models.elm, line 127 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJGpNUB7io_67aJ2SL:-KxJRHzTSpcvL97SfOQB:b-jjyde) ([raw file](https://github.com/hackerexperience/heborn/blob/8b1e0df377f5e87242c701ddec9629e084b30b60/src/Core/Models.elm#L127)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Can you use `Update.mapModel(setupOrPlay)` instead?
</blockquote></details>

Probably yes ^-^

---

*[src/Decoders/Setup.elm, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJHUZGdiPvVeg58Ur6:-KxJQI9MnnYBRI5THCdl:b-6kah2c) ([raw file](https://github.com/hackerexperience/heborn/blob/2d3cc2dc5ed842407586a6d3d7ca1d52c09e2c4a/src/Decoders/Setup.elm#L14)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

was this import used at all?
</blockquote></details>

better remove it

---

*[src/Game/Account/Models.elm, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-Kx9n8CN-Vi0NslK--7Q:-Kx9n8CPSVzsaKtNQczv:b-ae7719) ([raw file](https://github.com/hackerexperience/heborn/blob/31d7cb06df6e8060257e9b0454f4896f243d6b03/src/Game/Account/Models.elm#L27)):*
> ```Elm
> import Game.Meta.Types exposing (..)
> import Game.Network.Types exposing (NIP)
> import Setup.Types as Setup
> ```

TODO: remove me

---

*[src/Game/Servers/Settings/Types.elm, line 1 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJIEQDmH8LT8T3pZyy:-KxJQLcVaQjVinWicYzo:b-c1chn7) ([raw file](https://github.com/hackerexperience/heborn/blob/2d3cc2dc5ed842407586a6d3d7ca1d52c09e2c4a/src/Game/Servers/Settings/Types.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Oh, this should be documented...
I took me looking into 3 files to even understand what this was about!
(I'll mark as satisfied, but we need to start documenting, and list new features in PR, something like "What's new" or "Changelog", besides the other intel you are already giving)
</blockquote></details>

I don't even know if this folder is okay, but we need it 'cause it's the shortest way to implement this feature.

---

*[src/Setup/View.elm, line 39 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJJt9yDl4HeOHPhy28:-KxJQg4s1GRxf2xPEjKK:b2nhtan) ([raw file](https://github.com/hackerexperience/heborn/blob/2d3cc2dc5ed842407586a6d3d7ca1d52c09e2c4a/src/Setup/View.elm#L39)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

I should style this! :smirk: 
</blockquote></details>

Yup

---

*[src/Setup/Pages/Helpers.elm, line 10 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJKHDiDYIE6onPDvDP:-KxJQycJ8Zjb0EUfr8C_:b-q9vht) ([raw file](https://github.com/hackerexperience/heborn/blob/2d3cc2dc5ed842407586a6d3d7ca1d52c09e2c4a/src/Setup/Pages/Helpers.elm#L10)):*
> node contentNode attrs <|
>   <| flip (::) content
>   div [] [ h1 [] [ text " D'LayDOS" ] ]

3rd option maybe

---

*[src/Setup/Pages/Mainframe/Models.elm, line 32 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/294#-KxJL0sXF3z7VGtvWVpY:-KxJR2IhmcFsOC3ligyd:ba4v8hh) ([raw file](https://github.com/hackerexperience/heborn/blob/2d3cc2dc5ed842407586a6d3d7ca1d52c09e2c4a/src/Setup/Pages/Mainframe/Models.elm#L32)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

"Okay" means? Valid and not taken? Just valid? just not taken?
Though it doesn't matter must as Helix decides...
</blockquote></details>

isOkay = name is valid, no name conflicts for servers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/294)*

**Comment by kress95** [comment]
I think everything is alright now, but HOLD until we get production support.

**Comment by PedroHLC** [comment]
Approved to merge by @renatomassaro , production certificate expired so it's gonna be off for a while...

**Comment by kress95** [comment]
Merging it on #306

**Pull request closed without merging**
