### PR TITLE
Notifications: recreate

### PR DESCRIPTION
**Pull request by PedroHLC**
Follows #228

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/246)

### CODE REVIEW

**Comment by PedroHLC** [comment]
@renatomassaro Is this okay to Helix? This format would be related to notifications received through any means (bootstrap, event, onjoin server, etc)...

```json
{ "type": "simple"
   , "content": {"title": "Hello", "msg": "World"}
   , "created": 1506286664280
   , "read": 0
   }
```

```json
{ "type": "email_new"
   , "content": {"from": "XXXXXX", "msg": "Package received! Thank you master!"}
   , "created": 1506286664280
   , "read": 1
   }
```

**Comment by kress95** [comment]
Reviewed 42 of 54 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[src/Apps/Bug/Update.elm, line 40 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-xF2Yc68pd5t71Y_D:-Kv-xF2ZjRDgpRnZECwL:b-9sewuz) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Apps/Bug/Update.elm#L40)):*
> ```Elm
>             , Dispatch.toasts <|
>                 Toasts.Append Toasts.dummy
>             )
> ```

I think we should start using the new update format for apps too :|

---

*[src/Core/Update.elm, line 298 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-yhwKCSctTNN8Xv2V:-Kv-yhwKCSctTNN8Xv2W:b-locmm2) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Core/Update.elm#L298)):*
> ```Elm
>                             [ dispatchGame, dispatchOS ]
>                 in
>                     dispatcher model_ cmd dispatch
> ```

Going to use dispatch to send events? Then dispatch the game event too, this code is not consistent (manual update for game, dispatch for OS).

---

*[src/Decoders/Notifications.elm, line 14 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-z2f3eYYHflIyA1iE:-Kv-z2f3eYYHflIyA1iF:b-jrvqjn) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Decoders/Notifications.elm#L14)):*
> ```Elm
>    , "created": 1506286664280
>    , "read": 0
>    }
> ```

Put a line on that comment explaining that this is one of the expected formats you're decoding.  (no need for a verbose comment)

---

*[src/Game/Account/Dock/Models.elm, line 25 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-zW2uIUrxN97jGUOi:-Kv-zW2uIUrxN97jGUOj:byzo639) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Account/Dock/Models.elm#L25)):*
> ```Elm
>     , Apps.LanViewerApp
>     , Apps.EmailApp --TODO: Make campaign only
>     , Apps.BugApp -- TODO: Make dev only
> ```

This is TODO for another revision or WIP for this one?

---

*[src/Game/Notifications/Models.elm, line 59 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-zbwFdpY6wWJBRnKL:-Kv-zbwFdpY6wWJBRnKM:b-p72u22) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Notifications/Models.elm#L59)):*
> ```Elm
>         |> Dict.get pig
>         |> Maybe.map (\twin -> findId ( birth, from + 1 ) model)
>         |> Maybe.withDefault pig
> ```

Good, put a comment explaning how this works or renato will cut your fingers.

---

*[src/Game/Notifications/Update.elm, line 15 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-6E8EKQKWiBw4QRp:-Kv0-6E9yokIyADv-uPj:b-44pm9q) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Notifications/Update.elm#L15)):*
> ```Elm
>     case msg of
>         ReadAll ->
>             -- TODO: Add request to server
> ```

TODO for another PR, right?

---

*[src/OS/Header/Update.elm, line 128 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-ZeDOODgc1pKNTQs:-Kv0-ZeDOODgc1pKNTQt:b-gp9jkr) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Header/Update.elm#L128)):*
> ```Elm
> 
>         AccountReadAll ->
>             -- TODO
> ```

Todo for another revision? 

---

*[src/OS/Header/View.elm, line 63 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-l_DGYDLixJ7dne9:-Kv0-l_DGYDLixJ7dneA:bcknc5w) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Header/View.elm#L63)):*
> ```Elm
>             |> filterFunc
>             |> List.map Just
>             |> (::) Nothing
> ```

I would make it:
- A helper function on Game, that accepts Context and returns Maybe Servers.ID.
- A helper function on Servers, that accepts Context and returns Maybe Servers.Server.

---

*[src/OS/Toasts/Update.elm, line 97 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv00GR7glPFmH20dLNJ:-Kv00GR8eRTBKye4xxq7:b-8el5ie) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Toasts/Update.elm#L97)):*
> ```Elm
> delay time msg =
>     Process.sleep time
>         |> Task.perform (\_ -> msg)
> ```

:top:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/246)*

**Comment by PedroHLC** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[src/Apps/Bug/Update.elm, line 40 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-xF2Yc68pd5t71Y_D:-Kv3Kmlkaer1uewRjTl3:b-jh2m1n) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Apps/Bug/Update.elm#L40)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I think we should start using the new update format for apps too :|
</blockquote></details>

Not on every case, like this one, a small app with one message that can be treated with pipes, it would become just useless boilerplate

---

*[src/Core/Update.elm, line 298 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-yhwKCSctTNN8Xv2V:-Kv3LzTpOSn7YVebrRvY:bb71kmx) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Core/Update.elm#L298)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Going to use dispatch to send events? Then dispatch the game event too, this code is not consistent (manual update for game, dispatch for OS).
</blockquote></details>

Okay

---

*[src/Decoders/Notifications.elm, line 14 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-z2f3eYYHflIyA1iE:-Kv3M2Jv5PmcLEam0z1d:b-lqcnss) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Decoders/Notifications.elm#L14)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Put a line on that comment explaining that this is one of the expected formats you're decoding.  (no need for a verbose comment)
</blockquote></details>

Removing this comment, it existed for planning only

---

*[src/Game/Account/Dock/Models.elm, line 25 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-zW2uIUrxN97jGUOi:-Kv3_LHmV94swJqVdLmS:b-13gz07) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Account/Dock/Models.elm#L25)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

This is TODO for another revision or WIP for this one?
</blockquote></details>

Now tracked in #248

---

*[src/Game/Notifications/Models.elm, line 59 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-zbwFdpY6wWJBRnKL:-Kv3alDiIOrM4Edci3kQ:bb71kmx) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Notifications/Models.elm#L59)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Good, put a comment explaning how this works or renato will cut your fingers.
</blockquote></details>

Okay

---

*[src/Game/Notifications/Update.elm, line 15 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-6E8EKQKWiBw4QRp:-Kv3bDL_1TwYQlZgF9Pw:b-ipm4j0) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Game/Notifications/Update.elm#L15)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

TODO for another PR, right?
</blockquote></details>

Tracked in #249

---

*[src/OS/Header/Update.elm, line 128 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-ZeDOODgc1pKNTQs:-Kv3bJKmMwR3iYlKI0em:b-engayv) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Header/Update.elm#L128)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Todo for another revision? 
</blockquote></details>

Also, tracked in #249

---

*[src/OS/Header/View.elm, line 63 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-l_DGYDLixJ7dne9:-Kv3dG4tlmNs9hXtE_Us:b-jwa93r) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Header/View.elm#L63)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I would make it:
- A helper function on Game, that accepts Context and returns Maybe Servers.ID.
- A helper function on Servers, that accepts Context and returns Maybe Servers.Server.
</blockquote></details>

I've enhanced what I could, you're up next, tracking through #250

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/246)*

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Apps/Bug/Update.elm, line 40 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv-xF2Yc68pd5t71Y_D:-Kv3gomw-KSB_c0EevDW:b32w1t) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Apps/Bug/Update.elm#L40)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Not on every case, like this one, a small app with one message that can be treated with pipes, it would become just useless boilerplate
</blockquote></details>

Ok

---

*[src/Core/Update.elm, line 130 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv3guuJeDQ75XaHWxsK:-Kv3guuJeDQ75XaHWxsL:b2nid0f) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/Core/Update.elm#L130)):*
> ```Elm
> updateSetup : Msg -> Model -> SetupModel -> ( Model, Cmd Msg )
> updateSetup msg model stateModel =
>     -- DONE
> ```

thx

---

*[src/OS/Header/View.elm, line 63 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-Kv0-l_DGYDLixJ7dne9:-Kv3h5xOdbFs1zdbvsKT:b2nid0f) ([raw file](https://github.com/hackerexperience/heborn/blob/3580acb4f19ed93c9f47b282330ffa4e4091e688/src/OS/Header/View.elm#L63)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

I've enhanced what I could, you're up next, tracking through #250
</blockquote></details>

thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/246#-:-Kv3hlOLGW0UPSVNynaQ:bnfp4nl)*

**Pull request merged**
