### PR TITLE
Make notifications clickable

### PR DESCRIPTION
**Pull request by PedroHLC**
I love lasagna!

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/497)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Game/Account/Notifications/OnClick.elm, line 14 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oN2Ji8uNxTRWN5ROs:-L8oN2Ji8uNxTRWN5ROt:bb1pm6l) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/Game/Account/Notifications/OnClick.elm#L14)):*
> ```Elm
> 
>         NewEmail _ ->
>             config.openThunderbird
> ```

Clicking on it already marks it as read, right?

---

*[src/OS/Header/Config.elm, line 64 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oP6eg3IEgXdKnqvFc:-L8oP6eg3IEgXdKnqvFd:b5d5bkz) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Header/Config.elm#L64)):*
> ```Elm
>         config.onNewApp DBAdmin Nothing Nothing config.activeGatewayCId
>     , openExplorerInFile =
>         -- TODO: Explorer params
> ```

:robot: TODO FOUND

---

*[src/OS/Header/NotificationsView.elm, line 21 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oPCBCERQ46A7krTGz:-L8oPCBCERQ46A7krTH-:ba6otk2) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Header/NotificationsView.elm#L21)):*
Kek, actioner is a valid word for this context?

From some dictionary online:
> a film that features action, often extreme or violent; thriller

---

*[src/OS/Toasts/Config.elm, line 37 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oPSH_6MyKEiEtBgL2:-L8oPSH_6MyKEiEtBgL3:b-9vtxtu) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Toasts/Config.elm#L37)):*
> ```Elm
>         config.onNewApp DBAdmin Nothing Nothing config.activeGatewayCId
>     , openExplorerInFile =
>         -- TODO: Explorer params
> ```

:robot: ANOTHER TODO

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/497)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/OS/Header/NotificationsView.elm, line 21 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oPCBCERQ46A7krTGz:-L97gILpEJ4C_DRZj60J:b-flxwyc) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Header/NotificationsView.elm#L21)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Kek, actioner is a valid word for this context?

From some dictionary online:
> a film that features action, often extreme or violent; thriller
</blockquote></details>

Change the name to "ToMsg" if you can't find anything better.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/497)*

**Comment by PedroHLC** [comment]
Review status: 27 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Game/Account/Notifications/OnClick.elm, line 14 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oN2Ji8uNxTRWN5ROs:-L9Rcweg2JkLSfSPi36f:b1ox2j5) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/Game/Account/Notifications/OnClick.elm#L14)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Clicking on it already marks it as read, right?
</blockquote></details>

There is no individual reading anymore!

---

*[src/OS/Header/Config.elm, line 64 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oP6eg3IEgXdKnqvFc:-L9Rd1N3B0PTuCZAFjXD:b7g9sj8) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Header/Config.elm#L64)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

:robot: TODO FOUND
</blockquote></details>

Issue added

---

*[src/OS/Header/NotificationsView.elm, line 21 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oPCBCERQ46A7krTGz:-L9Rd4bl7MP_vnWy5vZF:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Header/NotificationsView.elm#L21)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Change the name to "ToMsg" if you can't find anything better.
</blockquote></details>

Done.

---

*[src/OS/Toasts/Config.elm, line 37 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/497#-L8oPSH_6MyKEiEtBgL2:-L9Rd92hAUuc_lVYhjRa:b-5wrpk2) ([raw file](https://github.com/hackerexperience/heborn/blob/998841855f91e8a4cc336fd41c942ee3eb4577ac/src/OS/Toasts/Config.elm#L37)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

:robot: ANOTHER TODO
</blockquote></details>

Issue added #500

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/497)*

**Comment by PedroHLC** [comment]
I'll squash this one into #501, so we have less work to merge it later...

**Pull request closed without merging**
