### PR TITLE
Improve change between game mode

### PR DESCRIPTION
**Pull request by themaxhero**
- [x] Use Server.type to identify the game model (instead of Server.mode)

This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/358)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/OS/Header/AccountView.elm, line 67 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/358#-L2MUVahk2YeZIgYUx0v:-L2MUVahk2YeZIgYUx0w:b3rr4dk) ([raw file](https://github.com/hackerexperience/heborn/blob/3ec742e06c0256b29d40fbdbb4aa35c4f30074b1/src/OS/Header/AccountView.elm#L67)):*
> ```Elm
>                             "Go Multiplayer"
>                         else
>                             "Go Campaign"
> ```

check if it gets more readable with |> pipes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/358)*

**Comment by kress95** [comment]
gibe rebase plox, I report u

**Comment by themaxhero** [comment]
*[src/OS/Header/AccountView.elm, line 67 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/358#-L2MUVahk2YeZIgYUx0v:-L2bSbeZenOX753xrTSF:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/3ec742e06c0256b29d40fbdbb4aa35c4f30074b1/src/OS/Header/AccountView.elm#L67)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

check if it gets more readable with |> pipes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/358)*

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 3 of 12 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Game/Servers/Dummy.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/358#-L2bUZb2EYAApSqgzCGt:-L2bUZb2EYAApSqgzCGu:b-pzpcez) ([raw file](https://github.com/hackerexperience/heborn/blob/73d3dbd7d6481978a57612101b09683677ac074b/src/Game/Servers/Dummy.elm#L1)):*
> ```Elm
> module Game.Servers.Dummy exposing (dummy)
> ```

no need for dummies in MASTER!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/358#-:-L2bUq0FcZg0GGtKf-qU:bnfp4nl)*

**Comment by themaxhero** [comment]
*[src/Game/Servers/Dummy.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/358#-L2bUZb2EYAApSqgzCGt:-L2bWPl9hgEELMh59B6-:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/73d3dbd7d6481978a57612101b09683677ac074b/src/Game/Servers/Dummy.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

no need for dummies in MASTER!!!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/358)*

**Comment by PedroHLC** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/358)*

**Pull request merged**
