### PR TITLE
Emails: add events

### PR DESCRIPTION
**Pull request by PedroHLC**
* on bootstrap
```json
{ "servers":...
, "story":
  { "emails":
    { "someone-id":
      { "messages":
        [ { "time":1505267765000.0
          , "direction":"sended"
          , "phrase":"001"
          }
        , { "time":1505267765001.0
          , "direction":"received"
          , "phrase":"002"
          }
        ]
      , "responses":["003", "004"]
      }
    }
  , "missions":
    { "mission": "some-mission-id"
    , "goals": "some-goal-id"
    , "current": "some-step-id"
    , "next": "some-step-id"
    }
  }
}
```
missions and goals are IDs, current and next are Step's IDs

* on `account` event `email.receive` like
```json
{ "from":"kress"
, "messages":
    [ { "time":1505267765000.0
      , "direction":"sended"
      , "phrase":"hello"
      }
    , { "time":1505267765001.0
      , "direction":"received"
      , "phrase":"hello"
      }
    ]
, "responses":["how are you?", "give me what I asked you!"]
}
```

@renatomassaro << Here are the events json example.

---
This change is?[Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/224)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Now, depends on #225

**Comment by renatomassaro** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/Events/Storyline/Emails.elm, line 86 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuUTlPajWX-0gp9a-i:-KtuUTlPajWX-0gp9a-j:by7ke6u) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Events/Storyline/Emails.elm#L86)):*
> ```Elm
> 
> 
> messageGuess : ( Float, String, String ) -> Decoder ( Float, Message )
> ```

Doc what this function does, why it exists. Or use a more intuitive name, like `getDirection` (or `oneDirection`)

---

*[src/Events/Storyline/Missions.elm, line 36 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuXAqXYX_T2ZsAy70y:-KtuXAqXYX_T2ZsAy70z:b-t5gmif) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Events/Storyline/Missions.elm#L36)):*
> ```Elm
> 
> 
> decoder : Decoder Model
> ```

We should probably discuss this format later today

---

*[src/Game/Storyline/Emails/Update.elm, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuVdLrJQZ4mLDtrMmi:-KtuVdLrJQZ4mLDtrMmj:b-o4oufk) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Emails/Update.elm#L30)):*
> ```Elm
> 
> 
> onReceive : ReceiveData -> Model -> UpdateResponse
> ```

Doc scenarios/when this event happens, what it does etc

---

*[src/Game/Storyline/Missions/Models.elm, line 7 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuWcBk0ACyag6SbJWg:-KtuWcBk0ACyag6SbJWh:b-b3wuzk) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Missions/Models.elm#L7)):*
> ```Elm
> 
> 
> type alias SyncID =
> ```

What is SyncID? Doc your types

---

*[src/Game/Storyline/Missions/Models.elm, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuWk22KvDJRfZcaly-:-KtuWk22KvDJRfZcaly0:b-ukmma0) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Missions/Models.elm#L26)):*
> ```Elm
>     = NoGoal
>     | TutorialIntroduction
> ```

TutorialIntroduction  should be part of `Tutorial` only, otherwise you can get an invalid state of missiong `NoMission` but goal `TutorialIntroduction`. 

---

*[src/Game/Storyline/Requests/Bootstrap.elm, line 10 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuW37x62uweVF5QE9U:-KtuW37x62uweVF5QE9V:bo5nlqh) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Requests/Bootstrap.elm#L10)):*
> ```Elm
> 
> 
> -- TODO: Clone decoder functions to here
> ```

If it's related to this PR, finish this todo before merging it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/224)*

**Comment by PedroHLC** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/Events/Storyline/Emails.elm, line 86 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuUTlPajWX-0gp9a-i:-KtvRv8UrthVzuBJXcNY:bxf5chr) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Events/Storyline/Emails.elm#L86)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Doc what this function does, why it exists. Or use a more intuitive name, like `getDirection` (or `oneDirection`)
</blockquote></details>

This is required as json uses strings and in Elm we use Unions for reasons like type-safety. It's not a getter and does nothing explicitly with direction, I can resume what it does to ```process decoded values to a suitable elm format handling failures in the process```
So maybe a ```safeToMessage```

---

*[src/Events/Storyline/Missions.elm, line 36 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuXAqXYX_T2ZsAy70y:-KtvUNNEZFdeadE4uiCp:b-nt7oxu) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Events/Storyline/Missions.elm#L36)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

We should probably discuss this format later today
</blockquote></details>

I'm in office all day today :office:  :clock10: 

---

*[src/Game/Storyline/Emails/Update.elm, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuVdLrJQZ4mLDtrMmi:-KtvU3ahZ8BQ3UK621h8:b-dwvlyv) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Emails/Update.elm#L30)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Doc scenarios/when this event happens, what it does etc
</blockquote></details>

I'll add some comments, and example is available on PR description

---

*[src/Game/Storyline/Missions/Models.elm, line 7 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuWcBk0ACyag6SbJWg:-KtvUAjvLzpVkKcBjG_0:b7b4zj8) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Missions/Models.elm#L7)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

What is SyncID? Doc your types
</blockquote></details>

I'll rename it do ID, as an alias to Game.Shared.ID

---

*[src/Game/Storyline/Missions/Models.elm, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuWk22KvDJRfZcaly-:-KtvUF08IyRLr5HVEfgC:bh6od2x) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Missions/Models.elm#L26)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

TutorialIntroduction  should be part of `Tutorial` only, otherwise you can get an invalid state of missiong `NoMission` but goal `TutorialIntroduction`. 
</blockquote></details>

Goals are reusable in btw missions

---

*[src/Game/Storyline/Requests/Bootstrap.elm, line 10 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuW37x62uweVF5QE9U:-KtvUYmOPTovj84MhzNP:b-h4ut51) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Game/Storyline/Requests/Bootstrap.elm#L10)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

If it's related to this PR, finish this todo before merging it.
</blockquote></details>

Kress wants to duplicate decoders btw Events and Bootstrap handlers so in the future they can have different specifications.
I don't see why do this unless they're already different (why generate useless javascript code and keep Elm boilerplate? also ABI is still unstable and both bootstrap and events may change in the same way along development creating chaos)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/224)*

**Comment by kress95** [comment]
Reviewed 6 of 14 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/Events/Storyline/Emails.elm, line 86 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/224#-KtuUTlPajWX-0gp9a-i:-KtwuP1f3itKRJTWG3gP:b-9zazbt) ([raw file](https://github.com/hackerexperience/heborn/blob/c34fd1979c9c22784e46eb825e9f9fe964d8eed0/src/Events/Storyline/Emails.elm#L86)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

This is required as json uses strings and in Elm we use Unions for reasons like type-safety. It's not a getter and does nothing explicitly with direction, I can resume what it does to ```process decoded values to a suitable elm format handling failures in the process```
So maybe a ```safeToMessage```
</blockquote></details>

Do not name that as safeToSomething, 99% of statically typed functional code must be safe, you should only mark  unsafe functions with an unsafe prefix (like haskell's unsafePerformIO).

I would name it as toMessageKV instead :T

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/224)*

**Comment by PedroHLC** [comment]
Reviewed 6 of 14 files at r1, 9 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/224)*

**Pull request merged**
