### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by kress95**
I'm improve some pain points here, most of the improvements will affect app implementations, it should be lotta easier to do dispatches to Game from now.

- [x] Rewrite Browse request
  - [x] Declaration
  - [x] Usage
- ~~Rewrite Remote Server Login~~ **CANCELLED**
  - ~~x Declaration~~
  - ~~x Usage~~
  - ~~o Dispatch effects~~
- ~~Rewrite Header.Config~~ **CANCELLED**
  - ~~x Declaration~~
  - ~~o Local Usage~~
  - ~~o Remote Usage~~
- [x] Rewrite OS.Config
  - [x] Declaration
  - [x] Local Usage
  - [x] Remote Usage
- [x] Rewrite WM.Config
  - [x] Declaration
  - [x] Local Usage
  - [x] Remote Usage

This change is needed due to the fact that _The Config Refactor_ was an asynchronous effort, I tried my best to communicate my intentions with it, but when comparing the way `Config` is handled in `Game` with how we have it in `OS`, it's clear that we had some problems.

> **NOTE:** to land this faster, I'm cancelling the death of Web, only its Browse request will be adopted.
> Adapting configs should be fast, I'm also cancelling the rewrite of `Header.Config`, mainly because it's 
> isolated enough to not cause any pains soon. I'm doing these changes because I'm changing my focus
>from fixing code issues to implementing game features.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/450)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/Game/Servers/Requests/Browse.elm, line 88 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L5ySTEioSMJ2LSelhGL:-L5ySTEkO-uuPbbUXeJX:b-uaois9) ([raw file](https://github.com/hackerexperience/heborn/blob/c72cb9c4545ec5e595d04ba8d17478f7a9756696/src/Game/Servers/Requests/Browse.elm#L88)):*
> ```Elm
> 
> 
> site : Site.Url -> Decoder Site
> ```

What about moving them to Decoders?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/Game/Servers/Requests/Browse.elm, line 88 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L5ySTEioSMJ2LSelhGL:-L5yudgYwsbEdFQUHNaC:bmm2fep) ([raw file](https://github.com/hackerexperience/heborn/blob/c72cb9c4545ec5e595d04ba8d17478f7a9756696/src/Game/Servers/Requests/Browse.elm#L88)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

What about moving them to Decoders?
</blockquote></details>

I wouldn't move it unless we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
I should note that I'm changing this PR focus to simplify our codebase. I'm simplifying and improving code quality for our OS configs and for some parts of Game too, it shouldn't take too long and will make our life easier for future extensions (no more config copy pasting yay).

**Comment by kress95** [comment]
**NOTE:** to land this faster, I'm cancelling the death of Web, only its Browse request will be adopted.
Adapting configs should be fast, I'm also cancelling the rewrite of `Header.Config`, mainly because it's
isolated enough to not cause any pains soon. I'm doing these changes because I'm going to change
my focus from fixing code issues to implementing game features.

**Comment by kress95** [comment]
I believe it's ready.

**Comment by PedroHLC** [comment]
Reviewed 67 of 68 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Apps/Browser/Launch.elm, line 27 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SF4p75mu4VMunkqwP:-L6SF4p75mu4VMunkqwQ:b-ad6bka) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Apps/Browser/Launch.elm#L27)):*
> ```Elm
> 
> launchOpenAtUrl : Config msg -> URL -> LaunchResponse msg
> launchOpenAtUrl config url =
> ```

Have you tested if this is working? It wasn't last time I checked...

---

*[src/Core/Config.elm, line 80 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SGTt3BLTSNhOkQmSN:-L6SGTt3BLTSNhOkQmSO:b-t7o67l) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Core/Config.elm#L80)):*
> ```Elm
> 
>         -- Leaved?
>         onLeaved _ _ =
> ```

Pick one: Left, Leave, Disconnected, Dropped
Wasn't this one being used to drop some server from endpoints list when logoff (before refactor)? Why wasn't this re-implemented?

---

*[src/Game/BackFlix/Models.elm, line 66 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SImDq94eVe1quva_m:-L6SImDq94eVe1quva_n:bo0j0z5) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Game/BackFlix/Models.elm#L66)):*
> ```Elm
> 
> 
> -- FIXME: these functions should affect model, not the Logs Type
> ```

"FIXME" founded? Is it gonna be ignored? Maybe "TODO: FIXME" ? Maybe create an issue for us to track it?

---

*[src/Game/Servers/Requests/Browse.elm, line 85 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SJ1ku5lANtcNUPYWg:-L6SJ1ku5lANtcNUPYWh:b29b4ho) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Game/Servers/Requests/Browse.elm#L85)):*
> ```Elm
>                 |> report_ "Servers.Browse" code flagsSrc
>                 |> Result.mapError (always <| ConnectionError url)
>                 |> Result.andThen Err
> ```

This line is breaking Reviewable colored syntax :rofl: 

---

*[src/OS/WindowManager/Config.elm, line 145 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SJd4J7mL66-7igfW-:-L6SJd4J7mL66-7igfW0:bulygo3) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L145)):*
> ```Elm
>             Tuple.first activeServer
> 
>         -- FIXME: review if passing down these seeds is okay
> ```

Is it?

---

*[src/OS/WindowManager/Config.elm, line 168 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SJjOwEYVInLNlw1RG:-L6SJjOwEYVInLNlw1RH:bddv5ti) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L168)):*
> ```Elm
>         , onSetContext = Account.HandleSetContext >> account config
> 
>         -- TODO: review if gateway cid usage is right
> ```

Yes, browser uses gateway cid for dns and login requests, you can remove this comment :smile: 

---

*[src/OS/WindowManager/Config.elm, line 264 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SKEe-BgbdR3IIrYMb:-L6SKEe-BgbdR3IIrYMc:b-897lry) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L264)):*
> ```Elm
>     , onCloseApp = config.toMsg <| Close windowId
> 
>     -- TODO: review if the CId usage is alright
> ```

FloatingHeads is "contextless" I think active server will always be gateway server... So it shouldn't really matter...

---

*[src/OS/WindowManager/Launch.elm, line 153 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/450#-L6SK_E3AqgsXNlB7MaP:-L6SK_E3AqgsXNlB7MaQ:bthj2g3) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Launch.elm#L153)):*
> ```Elm
>             launchAppHelper config
>                 activeGateway
>                 activeGateway
> ```

This is bizarre!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/Apps/Browser/Launch.elm, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SF4p75mu4VMunkqwP:-L6SftBoJFqgiQMISXV8:b-b6j64r) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Apps/Browser/Launch.elm#L27)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Have you tested if this is working? It wasn't last time I checked...
</blockquote></details>

Nope, gotta test it now.

---

*[src/Core/Config.elm, line 80 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SGTt3BLTSNhOkQmSN:-L6Sf8yHqwZmAyDMZngc:b-8qw853) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Core/Config.elm#L80)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Pick one: Left, Leave, Disconnected, Dropped
Wasn't this one being used to drop some server from endpoints list when logoff (before refactor)? Why wasn't this re-implemented?
</blockquote></details>

Gotta pick Left, this was never used before, it's dispatched after a channel is left.
If I recall correctly, we use the `Leave` action dispatch to remove from endpoints list, not this one

---

*[src/Game/BackFlix/Models.elm, line 66 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SImDq94eVe1quva_m:-L6Sd4RTr48ZMmbi-dY5:b3ltypt) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Game/BackFlix/Models.elm#L66)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

"FIXME" founded? Is it gonna be ignored? Maybe "TODO: FIXME" ? Maybe create an issue for us to track it?
</blockquote></details>

I'll create an issue for that, not going to fix it now. *DONE

---

*[src/Game/Servers/Requests/Browse.elm, line 85 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SJ1ku5lANtcNUPYWg:-L6SeqKF6s89fbF6RDK-:bvdcx7c) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Game/Servers/Requests/Browse.elm#L85)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

This line is breaking Reviewable colored syntax :rofl: 
</blockquote></details>

Too bad XD

---

*[src/OS/WindowManager/Config.elm, line 145 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SJd4J7mL66-7igfW-:-L6SeixJJkqiO5hffJNF:b-top0ny) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L145)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

seeds* == cids

---

*[src/OS/WindowManager/Config.elm, line 168 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SJjOwEYVInLNlw1RG:-L6SenwMeXeSkm_E_h6Z:bb6un1j) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L168)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Yes, browser uses gateway cid for dns and login requests, you can remove this comment :smile: 
</blockquote></details>

Done

---

*[src/OS/WindowManager/Config.elm, line 264 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SKEe-BgbdR3IIrYMb:-L6Sdzgy7tx5Z-YI2g1K:bz8ar7u) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L264)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

FloatingHeads is "contextless" I think active server will always be gateway server... So it shouldn't really matter...
</blockquote></details>

Yup, it's right ^^

---

*[src/OS/WindowManager/Launch.elm, line 153 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SK_E3AqgsXNlB7MaP:-L6SeHkSdLbRa4C629Kf:b-zgkb0m) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Launch.elm#L153)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

This is bizarre!
</blockquote></details>

But it's right :)
When launching a gateway context the active context and the active gateway are the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
Review status: 66 of 71 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/Apps/Browser/Launch.elm, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SF4p75mu4VMunkqwP:-L6Shqvv399EwVUK-8AH:b-n9u3e4) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Apps/Browser/Launch.elm#L27)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Nope, gotta test it now.
</blockquote></details>

The window is being opened, but the page isn't loading, I'll debug it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
Review status: 65 of 71 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/Apps/Browser/Launch.elm, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SF4p75mu4VMunkqwP:-L6Sja-pUg6se0xIh_fg:bqvp33t) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Apps/Browser/Launch.elm#L27)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

The window is being opened, but the page isn't loading, I'll debug it now.
</blockquote></details>

It's working now, it was a problem with the WM/Launch code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by kress95** [comment]
Review status: 65 of 71 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/OS/WindowManager/Config.elm, line 145 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SJd4J7mL66-7igfW-:-L6Sk1v79jZIuJnmAy-r:b-x54fjt) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/OS/WindowManager/Config.elm#L145)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

seeds* == cids
</blockquote></details>

This is the remaining one to discuss.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by themaxhero** [comment]
Reviewed 2 of 8 files at r1, 63 of 67 files at r2, 4 of 5 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/Apps/Browser/Config.elm, line 110 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6T8v8lKD632HwZx6yi:-L6T8v8n9UM7-LVHpwql:bvsq394) ([raw file](https://github.com/hackerexperience/heborn/blob/4cb9120caf06f7df271014ea0a906df4d5696422/src/Apps/Browser/Config.elm#L110)):*
> ```Elm
> 
> 
> endpoints : Config msg -> List CId
> ```

I liked that.

---

*[src/Apps/Browser/Launch.elm, line 27 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6TBW0nv2KeYnNq-exK:-L6TBW0nv2KeYnNq-exL:bvwhuit) ([raw file](https://github.com/hackerexperience/heborn/blob/4cb9120caf06f7df271014ea0a906df4d5696422/src/Apps/Browser/Launch.elm#L27)):*
> ```Elm
> 
> launchOpenAtUrl : Config msg -> URL -> LaunchResponse msg
> launchOpenAtUrl config url =
> ```

Isn't this function too big?

---

*[src/Apps/Browser/Models.elm, line 8 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6TBrJjOodbyoYtp1Hb:-L6TBrJjOodbyoYtp1Hc:bfcm5re) ([raw file](https://github.com/hackerexperience/heborn/blob/4cb9120caf06f7df271014ea0a906df4d5696422/src/Apps/Browser/Models.elm#L8)):*
> ```Elm
> import Game.Meta.Types.Network exposing (NIP)
> import Game.Servers.Filesystem.Shared as Filesystem
> import Game.Meta.Types.Network.Site as Site exposing (Site)
> ```

So much better.

---

*[src/Game/BackFlix/Models.elm, line 66 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-L6SImDq94eVe1quva_m:-L6TDPph-cjjULzrrgSP:b6onogb) ([raw file](https://github.com/hackerexperience/heborn/blob/41c2bcea7aa9900e36787aca424cf8f836ee4b81/src/Game/BackFlix/Models.elm#L66)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I'll create an issue for that, not going to fix it now. *DONE
</blockquote></details>

I think maybe the model could be changed to a Logs type insted of changing this functions.
I can't find out a scenario where can include anything else in this model.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450)*

**Comment by themaxhero** [comment]
---







*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/450#-:-L6TFe_lsAfV1jhNAGlF:bvvzact)*

**Pull request merged**
