### PR TITLE
Meta, Network, Session and Server integration

### PR DESCRIPTION
**Pull request by kress95**
I'll only merge it after merging the other ones.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/144)

### CODE REVIEW

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/144#-:-KnzLPKTSRJLXFGWBAyS:bnfp4nl)*

**Comment by kress95** [comment]
Just fixed the conflict :T

**Comment by PedroHLC** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/144)*

**Comment by PedroHLC** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/144)*

**Comment by PedroHLC** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/144)*

**Pull request merged**
