### PR TITLE
Hardware reimplementation

### PR DESCRIPTION
**Pull request by kress95**
### TODO

- [x] Properly react to motherboard attach/dettach.
- [x] Properly react to component link/unlink at hardware.
- [x] Properly react to component link/unlink at inventory.
- [x] Spec decoders.
- [x] Store the specs somehow
- [x] Finish Server Gears view.
- [x] Motherboard setup / update requests
- [x] Remove link/unlink and dispatch from hardware to inventory.
- [x] Tests

Wow 2757 lines PR Õ_Õ

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/335)

### CODE REVIEW

**Comment by renatomassaro** [comment]
With regards to `Component(Un)LinkedEvent`, how we are going to do when the whole motherboard changes? I mean, a MotherboardUpdate request might change several components. It's better to send a single event (`MotherboardChangedEvent`) with the "diff" (or the complete new motherboard), no? (pretty sure we've talked about this).

**Comment by renatomassaro** [comment]
> Wow 2215 lines PR Õ_Õ

- https://github.com/HackerExperience/Helix/pull/231
- https://github.com/HackerExperience/Helix/pull/322

noob :tipping_hand_woman:

**Comment by kress95** [comment]
This 981fdae commit is weird, I'll check it out.

**Comment by themaxhero** [comment]
*[src/Apps/ServersGears/Models.elm, line 31 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hm9-PB-g47atUYemr:-L0Hm9-QSDmJWfg14N1O:b1408lb) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Apps/ServersGears/Models.elm#L31)):*
> ```Elm
> 
> type Selection
>     = SelectingSlot Motherboard.Id
> ```

Motherboard.Id is kinda confusing, It looks like is the mobo id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
Reviewed 26 of 46 files at r1, 27 of 33 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[src/Apps/ServersGears/View.elm, line 45 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HneWR_GM2UJvSCshP:-L0HneWShn9ZgcQRC_85:b-wrb666) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Apps/ServersGears/View.elm#L45)):*
> ```Elm
> readonlyPanel : Game.Data -> Model -> Html Msg
> readonlyPanel data model =
>     -- TODO: when totals are available
> ```

:robot: TODO comment found

---

*[src/Decoders/Hardware.elm, line 7 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqnSF9lXHxFqBI_30:-L0HqnSG-N3sZMGCDrJS:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L7)):*
> ```Elm
>     exposing
>         ( Decoder
>         , succeed
> ```

unused

---

*[src/Decoders/Hardware.elm, line 8 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqoQkENmxYRgDXBok:-L0HqoQkENmxYRgDXBol:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L8)):*
> ```Elm
>         ( Decoder
>         , succeed
>         , fail
> ```

unused

---

*[src/Decoders/Hardware.elm, line 9 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqhnBrCbSeDCdW5YM:-L0HqhnBrCbSeDCdW5YN:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L9)):*
> ```Elm
>         , succeed
>         , fail
>         , bool
> ```

unused

---

*[src/Decoders/Hardware.elm, line 10 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqaCe657VTjXGnWRc:-L0HqaCe657VTjXGnWRd:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L10)):*
> ```Elm
>         , fail
>         , bool
>         , float
> ```

unused

---

*[src/Decoders/Hardware.elm, line 13 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqxC4Uto2lF4-DLID:-L0HqxC4Uto2lF4-DLIE:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L13)):*
> ```Elm
>         , string
>         , dict
>         , field
> ```

unused

---

*[src/Decoders/Hardware.elm, line 16 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hr1jKz4M3N45uJyva:-L0Hr1jKz4M3N45uJyvb:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L16)):*
> ```Elm
>         , maybe
>         , map
>         , andThen
> ```

unused

---

*[src/Game/Meta/Types/Network/Connections.elm, line 12 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hty2eQ8yLMKZ37W_G:-L0Hty2fOEFla9E3TBbI:b9v4x5x) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Meta/Types/Network/Connections.elm#L12)):*
> ```Elm
> 
> type alias Connections =
>     Dict NIP Connection
> ```

if Id and NIP in this context is the same thing, why not use Id insted of NIP?

---

*[src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm, line 5 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Huj1IfG5YTxOcJc7F:-L0Huj1J8zqo96o1tVMr:b-jmepyd) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm#L5)):*
> ```Elm
>         ( Response(..)
>         , request
>         , receive
> ```

unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[src/Apps/ServersGears/View.elm, line 45 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HneWR_GM2UJvSCshP:-L0HYREnSlm4itRuPHmC:b-udml2n) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Apps/ServersGears/View.elm#L45)):*
> ```Elm
> readonlyPanel : Game.Data -> Model -> Html Msg
> readonlyPanel data model =
>     -- TODO: when totals are available
> ```

They're really not available now, this is for later.

---

*[src/Game/Meta/Types/Network/Connections.elm, line 12 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hty2eQ8yLMKZ37W_G:-L0HYk7dMKbVrwlus_jW:bppfdt1) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Meta/Types/Network/Connections.elm#L12)):*
> ```Elm
> 
> type alias Connections =
>     Dict NIP Connection
> ```

My bad, it should really be Id :joy:

---

*[src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm, line 5 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Huj1IfG5YTxOcJc7F:-L0HYs2ilJKboj5IPO0a:bdlhqtr) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm#L5)):*
> ```Elm
>         ( Response(..)
>         , request
>         , receive
> ```

how can a module declaration be unsused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
*[src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm, line 5 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Huj1IfG5YTxOcJc7F:-L0Hc6z4SKsQW-zPjFEo:b7zasq1) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm#L5)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

how can a module declaration be unsused?
</blockquote></details>

Oops, my bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[src/Apps/ServersGears/Models.elm, line 31 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hm9-PB-g47atUYemr:-L0HZrzkkw_kyDJELL_q:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Apps/ServersGears/Models.elm#L31)):*
> ```Elm
> 
> type Selection
>     = SelectingSlot Motherboard.Id
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 7 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqnSF9lXHxFqBI_30:-L0H_k_jviXs73FxL0AF:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L7)):*
> ```Elm
>     exposing
>         ( Decoder
>         , succeed
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 8 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqoQkENmxYRgDXBok:-L0H_lu4HjXzTPvuUTBZ:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L8)):*
> ```Elm
>         ( Decoder
>         , succeed
>         , fail
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 9 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqhnBrCbSeDCdW5YM:-L0H_mcUlpT9qtlGeSM7:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L9)):*
> ```Elm
>         , succeed
>         , fail
>         , bool
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 10 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqaCe657VTjXGnWRc:-L0H_omDJ4BZs8uuzszn:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L10)):*
> ```Elm
>         , fail
>         , bool
>         , float
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 13 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0HqxC4Uto2lF4-DLID:-L0H_pRw65CgUcXrBHph:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L13)):*
> ```Elm
>         , string
>         , dict
>         , field
> ```

Done.

---

*[src/Decoders/Hardware.elm, line 16 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hr1jKz4M3N45uJyva:-L0H_qCdQ2izUk9KNJD9:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Decoders/Hardware.elm#L16)):*
> ```Elm
>         , maybe
>         , map
>         , andThen
> ```

Done.

---

*[src/Game/Meta/Types/Network/Connections.elm, line 12 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Hty2eQ8yLMKZ37W_G:-L0H_8QodXoAUA9kWp81:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Meta/Types/Network/Connections.elm#L12)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

My bad, it should really be Id :joy:
</blockquote></details>

Done.

---

*[src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm, line 5 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L0Huj1IfG5YTxOcJc7F:-L0H_LRAShXn04T3kVmY:b7wi2wj) ([raw file](https://github.com/hackerexperience/heborn/blob/79c5a78752d06350b94caddcd7ecf83368548ca3/src/Game/Servers/Hardware/Requests/UpdateMotherboard.elm#L5)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

how can a module declaration be unsused?
</blockquote></details>

Done. Found other things to remove here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-:-L0L77FWZ46_pCg1iSfJ:bnfp4nl)*

**Comment by themaxhero** [comment]
*[src/Decoders/Servers.elm, line 62 at r6](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L1tE4wvlYM2yBj5edD0:-L1tE4wvlYM2yBj5edD1:bbcmy3w) ([raw file](https://github.com/hackerexperience/heborn/blob/b35d36bdd2706cf75b101275c233535d9fdff374/src/Decoders/Servers.elm#L62)):*
> ```Elm
>         |> notifications
>         |> hardware
>         |> map (Debug.log "A Cute Motherboard")
> ```

What is "A Cute Motherboard"? A Miserable little pile of Debug.logs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
Reviewed 17 of 20 files at r6.
Review status: 53 of 54 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by kress95** [comment]
Review status: 53 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Decoders/Servers.elm, line 62 at r6](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-L1tE4wvlYM2yBj5edD0:-L1tJJ75hGj7wJwmKJZk:b-6h49gn) ([raw file](https://github.com/hackerexperience/heborn/blob/b35d36bdd2706cf75b101275c233535d9fdff374/src/Decoders/Servers.elm#L62)):*
<details><summary><i>Previously, themaxhero (Marcelo Amancio de Lima Santos) wrote…</i></summary><blockquote>

What is "A Cute Motherboard"? A Miserable little pile of Debug.logs?
</blockquote></details>

Done :joy: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Comment by themaxhero** [comment]
:lgtm:

---

Review status: 53 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335#-:-L1tMdirfL4q9vVcWY_i:bnfp4nl)*

**Comment by themaxhero** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/335)*

**Pull request merged**
