### PR TITLE
Add blank browser pages

### PR DESCRIPTION
**Pull request by PedroHLC**
That's just it. I've lost everything else, also, I've lost THE GAME!

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/174)

### CODE REVIEW

**Comment by kress95** [comment]
This PR title is not compatible with the commits, but no problem, just do not do that again.

**Comment by kress95** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/Apps/Browser/Pages/Home/View.elm, line 36 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpvtxHUhRvW3DpUy3Oq:-KpvtxHUhRvW3DpUy3Or:b-xgdse3) ([raw file](https://github.com/hackerexperience/heborn/blob/9f2e329cf75f26ebf5556d76228af4018d8846c8/src/Apps/Browser/Pages/Home/View.elm#L36)):*
> ```Elm
>             , li
>                 [ onClick <| BrowserGoAddress "lulapresoamanha.dmy" ]
>                 [ text "News" ]
> ```

2bad elm has no macros and we're forced to put lists everywhere

---

*[src/Game/Web/Dummy.elm, line 31 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpvuGwX4E2UvSxdPVSN:-KpvuGwX4E2UvSxdPVSO:bq64l9e) ([raw file](https://github.com/hackerexperience/heborn/blob/9f2e329cf75f26ebf5556d76228af4018d8846c8/src/Game/Web/Dummy.elm#L31)):*
> ```Elm
> 
>         _ ->
>             Unknown
> ```

this is what we get for not having erlang-like pattern matching

---

*[static/js/audio.js, line 14 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpvuTuP9ZBz5bJcJdXB:-KpvuTuP9ZBz5bJcJdXC:bee9rs3) ([raw file](https://github.com/hackerexperience/heborn/blob/9f2e329cf75f26ebf5556d76228af4018d8846c8/static/js/audio.js#L14)):*
> ```JavaScript
>     var audio = document.getElementById(id);
>     audio.pause();
> });
> ```

gibe eol pls

---

*[static/js/index.js, line 4 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpvtmbM4OXouM_kdC7o:-KpvtmbM4OXouM_kdC7p:bk8pjgu) ([raw file](https://github.com/hackerexperience/heborn/blob/9f2e329cf75f26ebf5556d76228af4018d8846c8/static/js/index.js#L4)):*
> ```JavaScript
> require('../css/fonts.css');
> 
> //require("leaflet_css");
> ```

wat man?n

---

*[static/js/map.js, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpvtrdaMLRm7YIgSBAs:-KpvtrdaMLRm7YIgSBAt:b-6apntm) ([raw file](https://github.com/hackerexperience/heborn/blob/9f2e329cf75f26ebf5556d76228af4018d8846c8/static/js/map.js#L13)):*
> ```JavaScript
> app.ports.mapCenter.subscribe(function(id, lat, long, zoom) {
>     map[id].setView([lat, long], zoom);
> });
> ```

gibe eol on eof pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/174)*

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 28 of 29 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/Apps/Subscriptions.elm, line 68 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpwI6LCJVwSJS3i_clS:-KpwI6LD6ZMeeF7PqeA-:barehq5) ([raw file](https://github.com/hackerexperience/heborn/blob/82fc371ca03ea4aefb121efa60706724c00cc2d7/src/Apps/Subscriptions.elm#L68)):*
> ```Elm
> 
>         LocationPickerModel model ->
>             LocationPicker.subscriptions data model
> ```

I'm not sure if we should keep this style or ```model |>``` :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-:-KpwIi6U4fN126Aowcw3:bnfp4nl)*

**Comment by kress95** [comment]
Review status: 68 of 69 files reviewed at latest revision, 5 unresolved discussions.

---

*[static/js/audio.js, line 14 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpwWDN6AywRuU2zWWn9:-KpwWDN75ha7WEaWvvAn:b-xhfftk) ([raw file](https://github.com/hackerexperience/heborn/blob/109a8654b027aa6e2a22c4be7cde8da52b5b5e89/static/js/audio.js#L14)):*
> ```JavaScript
>     var audio = document.getElementById(id);
>     audio.pause();
> });
> ```

no eols given

---

*[static/js/map.js, line 13 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-KpwdoqWit1k_YZU4UJs:-KpwdoqXiojdkYwyZ7QF:b-xhfftk) ([raw file](https://github.com/hackerexperience/heborn/blob/109a8654b027aa6e2a22c4be7cde8da52b5b5e89/static/js/map.js#L13)):*
> ```JavaScript
> app.ports.mapCenter.subscribe(function(id, lat, long, zoom) {
>     map[id].setView([lat, long], zoom);
> });
> ```

no eols given

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/174)*

**Comment by kress95** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/174)*

**Comment by PedroHLC** [comment]
* Rebased.
* EOF added before EOF on JS files.

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/174#-:-Kpzjy2ev4kRU9lDn_z4:bnfp4nl)*

**Pull request merged**
