### PR TITLE
Request Refactor

### PR DESCRIPTION
**Pull request by kress95**
This PR simplifies the way request works, it's still not ready, but not too far of being ready...

**There are some remaining problems:**

We need flags to build requests, because they contain the API url.

API url is only available at Core model level, so it's a little hard to get it without some changes on Game.

I couldn't think of easy ways for getting it, one of the ways was sending a NewRequest message like we usually do, I don't like how this rolls out.

[I'm talking solely about Game folder changes now]

The best solutions I found:

- replace CoreMsg with RequestMsg

or

- replace GameModel with CoreModel

The first solution is drastic, somewhat consistent with how Apps should cast GameMsg and Game should cast Requests. (so we properly catch them from Core and build the request there)

The second one the fast and easy way, it also looks more flexible as we could add more things to game that requires CoreModel.

I like both approaches.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/115)

### CODE REVIEW

**Comment by kress95** [comment]
Another option: pass down a partially applied function with core access.

**Comment by kress95** [comment]
**TODO:**

- [ ] Read Notification/Events
- [ ] Complete revision to remove comments and check for unnoticed removed things (could use some help)
- [ ] Re-add type annotations (also could use some help)

This PR pretty much melted my brains :joy:

**Comment by kress95** [comment]
Leftovers found:

- [ ] DispatchResponse
- [ ] Commented lines at src/Core/Update.elm
- [ ] Commented file src/Events/Models.elm
- [ ] Commented file src/Game/Events.elm
- [ ] Commented lines at src/Game/Messages.elm
- [ ] Commented lines at src/Game/Meta/Events.elm
- [ ] Commented lines at src/Game/Network/Events.elm
- [ ] Commented lines at src/Game/Servers/Events.elm 
- [ ] Commented lines at src/Game/Update.elm
- [ ] Delete file src/Landing/Login/Requests.elm
- [ ] Commented lines at src/Landing/Messages.elm
- [ ] Commented lines at src/Landing/SignUp/Messages.elm
- [ ] Delete file src/Landing/SignUp/Requests.elm
- [ ] Commented lines at src/Landing/SignUp/Update.elm
- [ ] Commented lines at  src/Landing/Update.elm
- [ ] Commented lines at src/OS/Messages.elm

**Comment by kress95** [comment]
Finally **DONE**

Things done here:

- `Request` framework is now simpler and less intrusive;
- The `Event` framework got a better shape, consistent with the newly refactored `Request` framework, sadly, the propagation still's as bad as before;
- `Logout` works as expected, but the models still aren't cleared, check #96 for discussing fixes to this problem;
- `CoreMsg` is now manually handled (on production) and there's also no message logging on production;
- Better message logging on development;
- Better API for controlling websockets, not as good as I wanted, but still better than before;

This comes with the cost fo changing 55 files, 1003 insertions, 1908 deletions :joy:

**Comment by PedroHLC** [comment]
Reviewed 39 of 48 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/115)*

**Pull request merged**
