### PR TITLE
Add Storage

### PR DESCRIPTION
**Pull request by kress95**
Not WIP, but with a **TODO**:
 
- Add issues for interface integration.
  - Explorer sidebar integration
  - Explorer download/upload modal integration
  - Notification storage display

I'm requesting special attention to notification changes, they maybe not okay, but the way we were doing was worse.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/325)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Still :lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/325#-:-KzfAxxZiihzLZF7g5Y9:b-2pygyf)*

**Comment by kress95** [comment]
Please do not merge me until backend implement `main_storage` field on `Server` bootstrap.

**Comment by PedroHLC** [comment]
Please do merge, let the backend break, I do like to work with untouchable history log!

**Comment by kress95** [comment]
11 files left for revision, can't merge without an ok

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 8 of 11 files at r3.
Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/325#-:-L-DWhLlM7PviuX6FJWo:bnfp4nl)*

**Comment by PedroHLC** [comment]
Reviewed 3 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/325)*

**Pull request merged**
