### PR TITLE
[PACK] TaskManager UI + Apps to new instances + overall enhancements

### PR DESCRIPTION
**Pull request by PedroHLC**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/106)

### CODE REVIEW

**Comment by renatomassaro** [comment]
:top: I'll review and possibly merge tonight

**Comment by renatomassaro** [comment]
FYI, `right click -> close` not working

**Comment by PedroHLC** [comment]
Yep, me and @kress95 noticed this yesterday (I did notified you through WPP). The close message used to be broadcast to every app, that is no longer.

**Comment by kress95** [comment]
Removed dependency on PR #103, I'll close it and we'll merge this one instead.

Reasons:

> This one includes every app updated and has some issues from PR #103 fixed, we don't want to waste time back-porting these fixes to PR #103.

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 16 of 33 files at r1, 52 of 61 files at r2, 9 of 9 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/106#-:-KmSlT8_5TDyxRMfglZS:bnfp4nl)*

**Pull request merged**
