### PR TITLE
Small refactor for SignUp and Login requests.

### PR DESCRIPTION
**Pull request by kress95**
Fixes the format of Landing requests to comply with the current standards.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/120)

### CODE REVIEW

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Landing/SignUp/Requests/SignUp.elm, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/120#-KmaBGUvFLvNgE9gsKT4:-KmaBGUvFLvNgE9gsKT5:b-8sgimx) ([raw file](https://github.com/hackerexperience/heborn/blob/20f0a28f7a4102c3d5960dcf0c5fbfe16f4c7ee0/src/Landing/SignUp/Requests/SignUp.elm#L38)):*
> ```Elm
> 
>         _ ->
>             -- WIP: handle error message (#117)
> ```

#117 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/120#-:-KmaBKvhmBk4QFO14dNh:bnfp4nl)*

**Comment by kress95** [comment]
I've done some changes with the request msg format... I'll try to fix #117 here, but #121 is my priority for now.

**Comment by PedroHLC** [comment]
Reviewed 4 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/120)*

**Comment by kress95** [comment]
I'm delaying the fix for sign-up errors, it's simple, but the current sign-up model is not so cooperative with joining local and server side validations.

**Pull request merged**
