### PR TITLE
Add Sidebar

### PR DESCRIPTION
**Pull request by PedroHLC**
About this PR:
Renato asked for a sidebar to useful information about player's active quests on the campaign mode, that could also be reused for multiplayer mode missions, it should be manually show-hidden, not opaque, one can expand-compact the missions individually.
But, I went ahead and decided it should accepts things more abstractly, so I abstracted it in  Widgets, Widgets can be spawned by the player (I called it Local Widgets) or by external factors (quests, missions, etc... - External Widgets), both, can be expanded / contracted in the toggle-able sidebar, also, player can order them, while us can give some of them priority.

This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/464)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 145 of 145 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/OS/WindowManager/Config.elm, line 126 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t1qh2awf8CgULsfom:-L6t1qh3Nz5dfFLoS0Oq:b-7jdmvw) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Config.elm#L126)):*
> ```Elm
>                 ( CampaingSidebarMsg
>                 , Just <| Game.getStory config.game
>                 )
> ```

smart

---

*[src/OS/WindowManager/Models.elm, line 45 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t-Y490oeEt4Q4H0lE:-L6t-Y490oeEt4Q4H0lF:btwb5jn) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Models.elm#L45)):*
> ```Elm
>     , appSize : Maybe Size
>     , campaingSidebar : Sidebar.Model
>     , multiplayerSidebar : Sidebar.Model
> ```

Hmm, this solution was bad for a WM, why is it okay for a sidebar?
I'm not unhappy or blocking anything here, I Just want to know if you understand the dispatch implications.

---

*[src/OS/WindowManager/Models.elm, line 1005 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t02akpYiaogD8U_Lb:-L6t02akpYiaogD8U_Lc:b-nvus7x) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Models.elm#L1005)):*
> ```Elm
>         getMultiplayerSidebar
>     else
>         getCampaingSidebar
> ```

This is probably better as a Config helper.

---

*[src/OS/WindowManager/Sidebar/Models.elm, line 125 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t9w_f8_2dQ3dYSXq_:-L6t9w_gNuykLdOAFmdT:bb7qx3u) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Models.elm#L125)):*
> ```Elm
>         |> Dict.get id
>         |> Maybe.withDefault untouchedExternal
> ```

wat?

---

*[src/OS/WindowManager/Sidebar/Generators/Story.elm, line 43 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6tAFqwxosWRV_yz1ZW:-L6tAFqwxosWRV_yz1ZX:b2s2ria) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Generators/Story.elm#L43)):*
> ```Elm
> 
>         Nothing ->
>             acu
> ```

What is this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/464)*

**Comment by kress95** [comment]
Another note, try doing these rename things in separate PRs, the main content of this PR is still in discussion and development phase... but I'm cool with the renames here, they could be merged if it was in another PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-:-L6wcUr3HFQ9jI8ItC2a:b-r2g8d3)*

**Comment by PedroHLC** [comment]
Review status: 104 of 128 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/OS/WindowManager/Models.elm, line 45 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t-Y490oeEt4Q4H0lE:-L6wiKilWPwKpIriTmhV:bp3aovt) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Models.elm#L45)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Hmm, this solution was bad for a WM, why is it okay for a sidebar?
I'm not unhappy or blocking anything here, I Just want to know if you understand the dispatch implications.
</blockquote></details>

Reverted!

---

*[src/OS/WindowManager/Sidebar/Models.elm, line 125 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6t9w_f8_2dQ3dYSXq_:-L6wiMf489H3ytMasUL1:b-evkgbb) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Models.elm#L125)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

wat?
</blockquote></details>

For view-generated elements that the user never touched (expanded/contracted, changed priority) there isn't an element on the dict, for those, this get generate a valid default-valued result

---

*[src/OS/WindowManager/Sidebar/Generators/Story.elm, line 43 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L6tAFqwxosWRV_yz1ZW:-L6wjC_0Zu2REQYZgW2Z:b341mka) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Generators/Story.elm#L43)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

a hack for view-generated (external) elements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/464)*

**Comment by kress95** [comment]
This should be merged if instances are really needed, but I want to better understand how some things works first.

---

Reviewed 1 of 162 files at r1, 24 of 25 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/OS/WindowManager/Models.elm, line 45 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6t-Y490oeEt4Q4H0lE:-L6x3RE-3AT0k7yz6TXH:b2nhv9m) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Models.elm#L45)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Reverted!
</blockquote></details>

^-^

---

*[src/OS/WindowManager/View.elm, line 49 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6x4iTcA3aAcn6DZjE6:-L6x4iTcA3aAcn6DZjE7:bz9gu3a) ([raw file](https://github.com/hackerexperience/heborn/blob/5019c465f305a58aaf0d471e5589399030b597bf/src/OS/WindowManager/View.elm#L49)):*
> ```Elm
> import OS.WindowManager.Shared exposing (..)
> import OS.WindowManager.Dock.View as Dock
> import OS.WindowManager.Sidebar.View as Sidebar
> ```

Please, could you explain me the ordering rules you're using?

---

*[src/OS/WindowManager/Sidebar/Models.elm, line 125 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6t9w_f8_2dQ3dYSXq_:-L6x5g4o6xy3To83pl7g:b9uwtl6) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Models.elm#L125)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

For view-generated elements that the user never touched (expanded/contracted, changed priority) there isn't an element on the dict, for those, this get generate a valid default-valued result
</blockquote></details>

Okay, I'm just having a hard time understanding what is an External widget. (this was already marked as satisfied, I'm just taking questions here)

---

*[src/OS/WindowManager/Sidebar/Models.elm, line 43 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6x6Cfq4HOAONRyQnRx:-L6x6Cfq4HOAONRyQnRy:b4f8zno) ([raw file](https://github.com/hackerexperience/heborn/blob/5019c465f305a58aaf0d471e5589399030b597bf/src/OS/WindowManager/Sidebar/Models.elm#L43)):*
> ```Elm
>     { isExpanded : Bool
>     , order : Int
>     }
> ```

I don't quite understand how these things work, what are external widgets?

---

*[src/OS/WindowManager/Sidebar/Generators/Story.elm, line 43 at r1](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6tAFqwxosWRV_yz1ZW:-L6x35k9DiDo28C8of-k:b-dyb6tt) ([raw file](https://github.com/hackerexperience/heborn/blob/2570b51e9d361273caa63da0450ec82e7b16886e/src/OS/WindowManager/Sidebar/Generators/Story.elm#L43)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

a hack for view-generated (external) elements
</blockquote></details>

I meant the whole module, never seen `Generators` name being used for anythink but tests, I want to understand if this is a pattern for something.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-:-L6x6a-x2hxFOqJiCZjQ:ba6dqzw)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/OS/WindowManager/Sidebar/Models.elm, line 196 at r2](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L6xB0BrCtee4z3GGiTH:-L6xB0BrCtee4z3GGiTI:b-e4xbhr) ([raw file](https://github.com/hackerexperience/heborn/blob/5019c465f305a58aaf0d471e5589399030b597bf/src/OS/WindowManager/Sidebar/Models.elm#L196)):*
> ```Elm
>             external
>             local
>             Dict.empty
> ```

I really don't understand what's happening :T

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/464)*

**Comment by kress95** [comment]
---

Reviewed 44 of 57 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Core/Update.elm, line 392 at r3](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L7bIC6JENl9xEoAOE2l:-L7bIC6JENl9xEoAOE2m:b8gwyn) ([raw file](https://github.com/hackerexperience/heborn/blob/feb9c092f9abcf36782b8db7621c662d3b96e411/src/Core/Update.elm#L392)):*
> ```Elm
> 
>         GameMsg (Game.BackFlixMsg _) ->
>             msg
> ```

good ^_^

---

*[src/UI/Elements/Spinner.elm, line 8 at r3](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-L7bIc1NC6HB-i9GhfB3:-L7bIc1NC6HB-i9GhfB4:b1vvgkb) ([raw file](https://github.com/hackerexperience/heborn/blob/feb9c092f9abcf36782b8db7621c662d3b96e411/src/UI/Elements/Spinner.elm#L8)):*
> ```Elm
> spinner : Html msg
> spinner =
>     node "spinner" [] []
> ```

We should use a fidget spinners for that

https://codepen.io/DHawku/pen/yXEZdq

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hackerexperience/heborn/464#-:-L7bKR-k4tv9CxfSu7fO:bvvzact)*

**Comment by PedroHLC** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/UI/Elements/Spinner.elm, line 8 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/464#-L7bIc1NC6HB-i9GhfB3:-L7bLo-mDUMRvMCSBgGm:b-xvx3g4) ([raw file](https://github.com/hackerexperience/heborn/blob/feb9c092f9abcf36782b8db7621c662d3b96e411/src/UI/Elements/Spinner.elm#L8)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

We should use a fidget spinners for that

https://codepen.io/DHawku/pen/yXEZdq
</blockquote></details>

That's max thing! I just moved it..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/464)*

**Pull request merged**
