### PR TITLE
Replace field access with apropriated functions

### PR DESCRIPTION
**Pull request by themaxhero**
* Replace field access with apropriated functions

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/375)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Not really reviewed, modifications were too similar...

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375#-:-L3-S_Hiwl_CZMkFyzlZ:b-vnaiix)*

**Comment by kress95** [comment]
---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375#-:-L3-dS4iwuNDjv3K0AGu:bvvzact)*

**Comment by kress95** [comment]
Ask jenkins to rebuild it, the build problem isn't your fault.

**Comment by kress95** [comment]
Reviewed 8 of 8 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/Apps/Launch.elm, line 154 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/375#-L34nUMBGclEgsKbPq8O:-L34nUMCftbY3vmzEYaC:b-2a8o5x) ([raw file](https://github.com/hackerexperience/heborn/blob/c009aa263a847a0e1dab12a2d021d686c857473c/src/Apps/Launch.elm#L154)):*
> ```Elm
> 
>         FloatingHeadsApp ->
>             FloatingHeads.initialModel Nothing reference
> ```

Compare with the Browser branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375)*

**Comment by themaxhero** [comment]
*[src/Apps/Launch.elm, line 154 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/375#-L34nUMBGclEgsKbPq8O:-L34rdPLFjZi9wiPVWFl:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/c009aa263a847a0e1dab12a2d021d686c857473c/src/Apps/Launch.elm#L154)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Compare with the Browser branch.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375)*

**Comment by kress95** [comment]
---

Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375#-:-L34sxO70MThGAPAxV_r:bvvzact)*

**Comment by kress95** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/375)*

**Pull request merged**
