### PR TITLE
Refactor Game.Servers.Logs.Update to use Configs

### PR DESCRIPTION
**Pull request by themaxhero**
Depends on #378 
* Refactor Game.Servers.Logs.Update to use Configs

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/379)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Is this WIP? Why is it conflicting?

**Comment by kress95** [comment]
I asked you to rebase it...

**Comment by kress95** [comment]
Reviewed 2 of 4 files at r2.
Review status: 2 of 40 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/379)*

**Comment by kress95** [comment]
Review status: 2 of 40 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Game/Servers/Logs/Config.elm, line 14 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/379#-L39cc3UhctMH76af2wd:-L39cc3UhctMH76af2we:b-4qxsvd) ([raw file](https://github.com/hackerexperience/heborn/blob/7cb1efff144def18f2dd0f5aca7b7038cfa53d1f/src/Game/Servers/Logs/Config.elm#L14)):*
> ```Elm
>     , toMsg : Msg -> msg
>     , cid : CId
>     , nip : NIP
> ```

Just a note here: You're not using nip anywhere, why requiring it here?
Side note 2: keep Cid, it'll be used for requests as soon as you imagine..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/379)*

**Comment by kress95** [comment]
Reviewed 4 of 4 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/379)*

**Comment by kress95** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/379)*

**Pull request merged**
