### PR TITLE
WindowManager refactor.

### PR DESCRIPTION
**Pull request by kress95**
I'm still working on it, but reviews are welcome 'cause this is a big PR and big PRs are error prone.

- [x] Fix Window leaks.
- [x] Fix Core.Config dispatches.
- [x] Fix some comments about WM behaviour.
- [x] Remove Browser.Update commented code.
- [x] Fix window menus.
- [x] Fix tests.
- [x] Add better code to manage endpoint apps.
- [x] Better yet launch code.

App instancing still's not fully lazy, but this is a hard feat to reach...

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/442)

### CODE REVIEW

**Comment by PedroHLC** [comment]
There is just one thing bothering me, Game and Apps don't have anything in common, and yet you put Desktop Apps inside Game Meta.

---

Reviewed 110 of 115 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/Browser/Config.elm, line 75 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5Fojb4A2QrUEC9HNmL:-L5Fojb4A2QrUEC9HNmM:b-ts3urq) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/Apps/Browser/Config.elm#L75)):*
> ```Elm
>         config.endpointCId
>             |> Maybe.map config.onOpenApp
>             |> Maybe.withDefault (always <| config.batchMsg [])
> ```

So, if there is no `endpointCId`, don't try anything at all?

---

*[src/OS/WindowManager/Helpers.elm, line 45 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5FsAW6yHPfd5HxmFdz:-L5FsAW6yHPfd5HxmFe-:bi6nj0r) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Helpers.elm#L45)):*
> ```Elm
> getWindowGateway : Config msg -> Model -> Window -> Maybe ( CId, Server )
> getWindowGateway config model window =
>     -- this function is kinda unsafe as some windows may not have a gateway
> ```

This is strange...

---

*[src/OS/WindowManager/Launch.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5FsVS1ufaWhFq4oAVy:-L5FsVS1ufaWhFq4oAVz:b4655z3) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Launch.elm#L1)):*
> ```Elm
> module OS.WindowManager.Launch exposing (launch)
> ```

Excellent code approach and quality!

---

*[src/OS/WindowManager/Models.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5Fso9izDIi4xo8Q3VW:-L5Fso9izDIi4xo8Q3VX:bi6rv7e) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Models.elm#L1)):*
> ```Elm
> module OS.WindowManager.Models exposing (..)
> ```

Awesome and beautiful code!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-:-L5FppVOAigeG5QqMcJW:b-qu5z66)*

**Comment by kress95** [comment]
I'm asking for additional review.

**Comment by kress95** [comment]
> There is just one thing bothering me, Game and Apps don't have anything in common, and yet you put Desktop Apps inside Game Meta.

Game and Apps have some dependencies:

- Game.Account stores dock apps order
- We need a communication method between Game and Apps, this is Reference
- We need a communication method between Game and Browser Tabs, this is Requester

Removing these 3 things or allowing them to exist without custom types will remove Game/Meta/Types/Apps, I'm accepting suggestions on that here.

Note: The communication methods between Game & Browser Tabs may die once we update DNS requests.

---

Reviewed 115 of 115 files at r1.
Review status: 105 of 111 files reviewed at latest revision, all discussions resolved.

---

*[src/Apps/Browser/Config.elm, line 75 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5Fojb4A2QrUEC9HNmL:-L5JPzKDAcc0RiTF_QOA:b39nh5b) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/Apps/Browser/Config.elm#L75)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

So, if there is no `endpointCId`, don't try anything at all?
</blockquote></details>

The correct behaviour is to store page CId somewhere instead of collecting it from Config...
I don't know if it should be fixed exactly *now*

---

*[src/OS/WindowManager/Helpers.elm, line 45 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5FsAW6yHPfd5HxmFdz:-L5JQR8zwzrzfNGiChPh:b-2ntfef) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Helpers.elm#L45)):*
> getWindowGateway 

Not strange, the new WM allows having endpoint-only apps, this is where this problem rises... We have no windows like that for now, so no problem ^^

---

*[src/OS/WindowManager/Launch.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5FsVS1ufaWhFq4oAVy:-L5JRKT_TXQhthvK2u3D:blpw4ho) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Launch.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Excellent code approach and quality!
</blockquote></details>

The new code isn't as bright as it was, but this system is complex as f*ck...

---

*[src/OS/WindowManager/Models.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5Fso9izDIi4xo8Q3VW:-L5JRqEWY3O8PoDscONP:bs8jbsn) ([raw file](https://github.com/hackerexperience/heborn/blob/b71a5f764b9c36a28fc9df155700d0bfdefac652/src/OS/WindowManager/Models.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Awesome and beautiful code!
</blockquote></details>

I'm happier with the Update, but this model code is what simplified that update so much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-:-L5JOwZXxMzltMRwMxi5:b-6fq13q)*

**Comment by kress95** [comment]
Review status: 105 of 111 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/OS/WindowManager/Update.elm, line 143 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-L5JiEcscrY98jMg3kSJ:-L5JiEcscrY98jMg3kSK:b-n13ieb) ([raw file](https://github.com/hackerexperience/heborn/blob/4b282a01a2f6cde9aeec1e8e6e19e8b3de81c800/src/OS/WindowManager/Update.elm#L143)):*
> ```Elm
> 
>             Nothing ->
>                 launch config desktopApp (Just params) maybeContext model
> ```

It just got to my attention that this code is half wrong, I'll try to fix it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/442)*

**Comment by kress95** [comment]
Shall we accept this PR as it is and improve its debts later?

**Comment by PedroHLC** [comment]
Yes sir! (That's ok cause you made an issue)

---

Reviewed 1 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/442#-:-L5PLXSP5TmfIBffULQP:b-x1d4vi)*

**Comment by kress95** [comment]
I'm working on some improvements: I'll push if I get them ready today, and otherwise merge.

**Pull request merged**
