### PR TITLE
Remove Requests channel.

### PR DESCRIPTION
**Pull request by kress95**
Bye bye

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/320)

### CODE REVIEW

**Comment by themaxhero** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/320#-:-Kz64gqpVlQixgq5zTOd:bnfp4nl)*

**Comment by themaxhero** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/320)*

**Comment by themaxhero** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/320)*

**Comment by renatomassaro** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/320#-:-Kz6KmYGgFVLDCTtMY5i:bnfp4nl)*

**Pull request merged**
