### PR TITLE
[PACK] Overall progress

### PR DESCRIPTION
**Pull request by PedroHLC**
Requires #106,  #110,  #112.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/114)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Apps and Game are so happy together now! 💟

**Comment by PedroHLC** [comment]
Re-adopted master 🥇

**Comment by kress95** [comment]
Tests are passing locally (and I could rebase it locall without any conflict... so jenkins is drunk).
I'll review it.

**Comment by kress95** [comment]
Reviewed 43 of 59 files at r1, 18 of 23 files at r2, 16 of 16 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/Apps/Explorer/Menu/Models.elm, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/114#-KmbWde7DcNzYSu0V5-V:-KmbWde7DcNzYSu0V5-W:blh8p91) ([raw file](https://github.com/hackerexperience/heborn/blob/15ca23900b6964963e1f6c61e2e76205b160af75/src/Apps/Explorer/Menu/Models.elm#L14)):*
> ```Elm
>     | MenuExecutable FileID
>     | MenuActiveAction FileID
>     | MenuPassiveAction FileID
> ```

I don't like it but I don't know if there's a better way to do it. (let's leave it as it's now to see how it scale)

---

*[src/Apps/Explorer/Menu/View.elm, line 91 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/114#-KmbXITbsEhsSVUwNxvt:-KmbXITbsEhsSVUwNxvu:b-yy7uec) ([raw file](https://github.com/hackerexperience/heborn/blob/15ca23900b6964963e1f6c61e2e76205b160af75/src/Apps/Explorer/Menu/View.elm#L91)):*
> ```Elm
>               , ( ContextMenu.item "Stop", MenuClick Dummy )
>               ]
>             ]
> ```

Leave it as it is now, but I strongly believe that every instance functions with giant pattern matching should be split on smaller functions.

Compare [Game.Update](https://github.com/HackerExperience/HEBorn/blob/master/src/Game/Update.elm) with [Core.Update](https://github.com/HackerExperience/HEBorn/blob/master/src/Core/Update.elm), you will see what reads and scales better.

---

*[src/Apps/LogViewer/Update.elm, line 96 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/114#-KmbYevqbbDxI5l5J300:-KmbYevqbbDxI5l5J301:b-dpwgb3) ([raw file](https://github.com/hackerexperience/heborn/blob/15ca23900b6964963e1f6c61e2e76205b160af75/src/Apps/LogViewer/Update.elm#L96)):*
> ```Elm
>                     ]
>             in
>                 ( model, Cmd.none, gameMsg )
> ```

Same comment as before, leave it as it's...
But we should really make a refactor plan to make our coding style consistent, and a code style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/114)*

**Comment by PedroHLC** [comment]
Jenkins was [successful](https://ci.hackerexperience.com/blue/organizations/jenkins/HackerExperience%2FHEBorn/detail/merge-try/2/pipeline) on merge-try branch.
Revised by @kress95.
I'll be merging this through "merge-try" and closing this one...

**Comment by kress95** [comment]
I'm not sure why jenkins is giving trouble, there's no conflicts...

**Pull request closed without merging**
