### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by PedroHLC**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/451)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Core/Update.elm, line 350 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-L5z1VrO4clj6eEe_Zot:-L5z1VrPk66OqvIazXSW:b-ngoenz) ([raw file](https://github.com/hackerexperience/heborn/blob/0b1548ef7efda6b8094d7a9f2750275043e6fc24/src/Core/Update.elm#L350)):*
> ```Elm
>                 msgs
>                     |> List.map received
>                     |> BatchMsg
> ```

**MUDA MUDA MUDA MUDA MUDA MUDA**

Do you even checked how `received` is used? This change will make it print the same message multiple times.
And do not log empty BatchMsg, it's supposed to be a NoOp. (why bother logging it?)

---

*[src/Game/Web/Requests/DNS.elm, line 115 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-L5z278XUIrSTktT72lp:-L5z278XUIrSTktT72lq:bfl3bxb) ([raw file](https://github.com/hackerexperience/heborn/blob/0b1548ef7efda6b8094d7a9f2750275043e6fc24/src/Game/Web/Requests/DNS.elm#L115)):*
> ```Elm
> 
>         "npc_isp" ->
>             succeed ISP
> ```

Got it, gotta change it here, but next time make a note on my PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/451)*

**Comment by themaxhero** [comment]
---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-:-L5zBuhYFGYndSc0cFA8:bvvzact)*

**Comment by PedroHLC** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Core/Update.elm, line 350 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-L5z1VrO4clj6eEe_Zot:-L5zBtNAAiHcAaeCJbZs:b-4xxnll) ([raw file](https://github.com/hackerexperience/heborn/blob/0b1548ef7efda6b8094d7a9f2750275043e6fc24/src/Core/Update.elm#L350)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

**MUDA MUDA MUDA MUDA MUDA MUDA**

Do you even checked how `received` is used? This change will make it print the same message multiple times.
And do not log empty BatchMsg, it's supposed to be a NoOp. (why bother logging it?)
</blockquote></details>

Ok, map can be removed, but I did needed to see an empty BatchMsg to notice what was wrong with, onInput, without seeing it I couldn't even start to imagine why was it happening, and after that I had to search every "batchmsg []" to find where it was wrong. So, it indeed became useful to print this debug info!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/451)*

**Comment by kress95** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Core/Update.elm, line 347 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-L5zQ1niW9yOaQJ9gPOB:-L5zQ1niW9yOaQJ9gPOC:bnmqwyz) ([raw file](https://github.com/hackerexperience/heborn/blob/6d513b8cbb94b1586490595cd0450cddfe65d41f/src/Core/Update.elm#L347)):*
> ```Elm
> 
>         -- ignored messages
>         BatchMsg _ ->
> ```

Great, now it's good, remember to avoid List.length (it's O(n)) and to try to reuse cases when possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/451#-:-L5zQByuz5diAQJLG-v5:bg7igkv)*

**Pull request merged**
