### PR TITLE
Tango is back

### PR DESCRIPTION
**Pull request by PedroHLC**
Imgur
The supreme lightweight mp3 player now on HEBorn! Hail Winamp!

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/148)

### CODE REVIEW

**Comment by kress95** [comment]
This is what you do on your free time? :joy:
You could be creating an optimal lambda calculus evaluator or something better :joy: :joy: :joy:

**Comment by PedroHLC** [comment]
Of course is serious, this is gorgeous, I just have to remove Madonna song, I think it's copyrighted...

**Comment by kress95** [comment]
Undecorated windows are nice, but wth man :v

**Comment by kress95** [comment]
I would surely merge it if this used localstorage instead of an url :v

**Comment by PedroHLC** [comment]
Will be closed for now to reborn later way better.

**Pull request closed without merging**
