### PR TITLE
Replace Dispatch with a better thing

### PR DESCRIPTION
**Pull request by kress95**
### TODO

- [x] Experimentation with a replacement for `Dispatcher`.
- [x] Experimentation with a better format for `simple Requests`.
- [x] Example of how it works on `Game.Servers.Processes`.
- [x] Fix the "`Game.Notifications` is shit" problem.

After fixing the last one, this gets merged.

### NOTES

I'm finally allowing you guys to use the `fromMsg : Msg -> Cmd Msg` hack, it shoud be used when the new "simple requests" system isn't enough, do not abuse it.

You may find the hack at `Utils.Cmd`, use it wisely.

Another thing: multiMsg was renamed to batchMsg, mainly to fit better with Elm style, and a cool thing about it: We get a free NoOp msg from it for free, just use `config.batchMsg []` to get it, no need for smelly `NoOp` messages anymore, yay 😄 

Yet another thing: many things are getting deprecated fast, I'm making the replacement functions with _ suffixes to avoid breaking tons of old code, I'll clean it all after completing the **PLANS** section bellow (on later PRs)

This is a monster of PR, but it's almost ready.

Notes to everyone: Abuse from */Shared, this PR includes an example of it, i'm asking: try to move functions that can be used by outsiders to a shared file, t will help a lot with partial compilation times of our `Models`.

### PLANS

- Remake our 25 requests to use the new format, this is a task that requires attention.
- Kill events, this is a task that doesn't allow team work.
- Kill dispatcher in Game, this might be a task that allows team work.
- Remove every unused import, this is a task for a script, somebody code it please.

Fixing that finishes the high brain usage part of our refactor, the rest should be a breeze;

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/398)

### CODE REVIEW

**Comment by PedroHLC** [comment]
I approve this PR, I approve it a lot!

---

Reviewed 56 of 56 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Game/Servers/Processes/Update.elm, line 1 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/398#-L3Dznyh6jACGuU7_5JR:-L3Dznyj5f-JCQddcROi:b-pyg00p) ([raw file](https://github.com/hackerexperience/heborn/blob/a024213e213d36e23eec847e50df745414546ed7/src/Game/Servers/Processes/Update.elm#L1)):*
> ```Elm
> module Game.Servers.Processes.Update exposing (update)
> ```

This is the first modification that I see that I really believe you help us!

---

*[src/Requests/Requests.elm, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/398#-L3E-qZIl0XXn9tIUS9i:-L3E-qZIl0XXn9tIUS9j:bx142pr) ([raw file](https://github.com/hackerexperience/heborn/blob/a024213e213d36e23eec847e50df745414546ed7/src/Requests/Requests.elm#L22)):*
> ```Elm
> 
> 
> -- remove underlines after deprecating legacy functions
> ```

Add a "REVIEW" tag or invent one for this case "CONFREFACT", so we can track this kind of thing later!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/398#-:-L3E-Z9RTGhAUOYqBV-H:bovqwq9)*

**Comment by kress95** [comment]
Note, I disabled some notification features because I changed how notifications work, this isn't related to compilation speed, it's a code quality problem, the new notifications are better, but are still not properly integrated with anything but processes.

We're expected to reimplement the disabled Notifications feats in following PRs.

**Comment by kress95** [comment]
Review status: 44 of 90 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Game/Servers/Processes/Update.elm, line 1 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/398#-L3Dznyh6jACGuU7_5JR:-L3AWpQEDi79zvZ_Y_c-:bgc7vqv) ([raw file](https://github.com/hackerexperience/heborn/blob/a024213e213d36e23eec847e50df745414546ed7/src/Game/Servers/Processes/Update.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

This is the first modification that I see that I really believe you help us!
</blockquote></details>

:heart: 

---

*[src/Requests/Requests.elm, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/398#-L3E-qZIl0XXn9tIUS9i:-L3AXnrBVWPW6fyLHtc8:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/a024213e213d36e23eec847e50df745414546ed7/src/Requests/Requests.elm#L22)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Add a "REVIEW" tag or invent one for this case "CONFREFACT", so we can track this kind of thing later!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/398)*

**Comment by themaxhero** [comment]
Reviewed 1 of 56 files at r1, 48 of 48 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/398)*

**Pull request merged**
