### PR TITLE
Implement FloatingHeads App

### PR DESCRIPTION
**Pull request by themaxhero**
* Implement FloatingHeads App
- [x] Model
- [x] Logic
- [x] View

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/368)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Apps/Update.elm, line 248 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2xTDOFA-vZ6U2NN3Ti:-L2xTDOFA-vZ6U2NN3Tj:b2ni698) ([raw file](https://github.com/hackerexperience/heborn/blob/024f9fcec6406979e1142c5d460de58554194d2f/src/Apps/Update.elm#L248)):*
> ```Elm
> --      map CalculatorModel CalculatorMsg (Calculator.update data msg model)
> --  ( FloatingHeadsMsg msg, FloatingHeadsModel model ) ->
> --      map FloatingHeadsModel FloatingHeadsMsg (FloatingHeads.update data msg model)
> ```

kek

---

*[src/Apps/Email/Messages.elm, line 10 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2xTKPg1HQabpGQtLiZ:-L2xTKPg1HQabpGQtLi_:bb7qx3u) ([raw file](https://github.com/hackerexperience/heborn/blob/4873512c987b2f290b8beab7ffd8872807b679cb/src/Apps/Email/Messages.elm#L10)):*
> ```Elm
>     = MenuMsg Menu.Msg
>     | SelectContact String
>     | Reply Content
> ```

wat?

---

*[src/Apps/Email/Resources.elm, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2xTNp8jX5Or5qN1jfS:-L2xTNp8jX5Or5qN1jfT:bymi58v) ([raw file](https://github.com/hackerexperience/heborn/blob/4873512c987b2f290b8beab7ffd8872807b679cb/src/Apps/Email/Resources.elm#L11)):*
> ```Elm
>     | From
>     | To
>     | Sys
> ```

anyway to explain these changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by themaxhero** [comment]
*[src/Apps/Email/Messages.elm, line 10 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2xTKPg1HQabpGQtLiZ:-L2xWA4T-A6_1ELHHB7K:b-3yjfa) ([raw file](https://github.com/hackerexperience/heborn/blob/4873512c987b2f290b8beab7ffd8872807b679cb/src/Apps/Email/Messages.elm#L10)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

wat?
</blockquote></details>

Maybe i should use Person type.
But this is what should dispatch the contact to FloatingHeads

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by themaxhero** [comment]
*[src/Apps/Email/Resources.elm, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2xTNp8jX5Or5qN1jfS:-L2xWTmNWxLa2blIcYda:b-v9yej7) ([raw file](https://github.com/hackerexperience/heborn/blob/4873512c987b2f290b8beab7ffd8872807b679cb/src/Apps/Email/Resources.elm#L11)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

anyway to explain these changes?
</blockquote></details>

Because Email will now be a contact list that calls FloatingHeads with the Current Contact,
This Image tag should be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by kress95** [comment]
I'll require extra input from @PedroHLC, but looks good.
Is everything working all right? I won't have time to test it now... (maybe later)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-:-L2wtdMPa3DmyFGoOY_J:b739rxp)*

**Comment by PedroHLC** [comment]
Reviewed 32 of 36 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[src/Apps/Email/Models.elm, line 30 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1Tuz_itvvWBDD_B1:-L2z1Tuz_itvvWBDD_B2:b-6i1vdo) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Models.elm#L30)):*
> ```Elm
> initialModel =
>     { menu = Menu.initialMenu
>     , activeContact = Nothing
> ```

No need anymore for `activeContact`, pls remove it.
Do the same to `getActiveContact` and  `setActiveContact`

---

*[src/Apps/Email/Resources.elm, line 5 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0kSR_bit8mv0P9yk:-L2z0kSSK3f8nsDxOWyP:b-hi0hkv) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Resources.elm#L5)):*
> ```Elm
> 
> type Classes
>     = Super
> ```

There shouldn't be a need for a "Super" anymore...

---

*[src/Apps/Email/Style.elm, line 19 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0sVDJMDkVIqCIdA2:-L2z0sVDJMDkVIqCIdA3:b-z99mhn) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Style.elm#L19)):*
> ```Elm
>             , width (pct 100)
>             , children
>                 [ class Contacts
> ```

Move "Contacts" up, remove "Super"

---

*[src/Apps/Email/Style.elm, line 23 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0yblEjqJIfAvwxs7:-L2z0yblEjqJIfAvwxs8:bt7p6bb) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Style.elm#L23)):*
> ```Elm
>                     , overflowY auto
>                     , overflowX hidden
>                     , width (pct 100)
> ```

`width (pct 100)` is `display block`(DIV's default display) default behaviour!

---

*[src/Apps/Email/View.elm, line 32 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1iuV-_iDwcZnRVi9:-L2z1iuV-_iDwcZnRViA:b-fvmezp) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/View.elm#L32)):*
> ```Elm
>                 |> Game.getGame
>                 |> Game.getStory
>                 |> Storyline.getEmails
> ```

Thanks, this is better!

---

*[src/Apps/Email/View.elm, line 48 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1p9t-PcT-C3A_JAN:-L2z1p9t-PcT-C3A_JAO:bljp08y) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/View.elm#L48)):*
> ```Elm
> 
> 
> contactProcessor :
> ```

why `contactProcessor`? Why not just `contact`?

---

*[src/Apps/Email/View.elm, line 78 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1yfoNh3u8xE7E372:-L2z1yfoNh3u8xE7E373:b-dyxg1w) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/View.elm#L78)):*
> ```Elm
>             , Css.height (Css.px 48)
>             , Css.borderRadius (Css.pct 100)
>             ]
> ```

Why isn't this in a CSS Class (inside Style file)? If this rule is static, move it to there...

---

*[src/Apps/FloatingHeads/Models.elm, line 40 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z5fmec9MiGc_vkHRw:-L2z5fmec9MiGc_vkHRx:bm1de07) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Models.elm#L40)):*
> ```Elm
>     { me = me
>     , menu = Menu.initialMenu
>     , activeContact = "friend"
> ```

This is not the FP approach, but this "fallback" seems fine to me!

---

*[src/Apps/FloatingHeads/Resources.elm, line 16 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z6MFAhHr-IdYDsYDZ:-L2z6MFAhHr-IdYDsYD_:b-xk9e6i) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Resources.elm#L16)):*
> ```Elm
>     | WindowHeaderButtons
>     | HeaderButtons
>     | HeaderBtnClose
> ```

Were all this classes really required? why not only a Header and HeaderBtnClose?

---

*[src/Apps/FloatingHeads/Resources.elm, line 21 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z5srPuha8ElZ_YcBI:-L2z5srPuha8ElZ_YcBJ:b-ckozzb) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Resources.elm#L21)):*
> ```Elm
> prefix : String
> prefix =
>     "floating-heads"
> ```

Too big! This is a prefix for the classes when already on HTML side, make it smaller pls!

---

*[src/Apps/FloatingHeads/Update.elm, line 100 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7FXIQF2SeuVfYywW:-L2z7FXIQF2SeuVfYywX:b-89m9rb) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Update.elm#L100)):*
> ```Elm
>     let
>         dispatch =
>             Dispatch.os <| OS.CloseApp model.me
> ```

Cute!

---

*[src/Apps/FloatingHeads/View.elm, line 132 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7P3m9hAiJXtqTUuT:-L2z7P3m9hAiJXtqTUuU:br831cb) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L132)):*
> ```Elm
>     , Css.borderRadius (Css.pct 100)
>     ]
>         |> styles
> ```

Again, if this is static, then it should be a CSS Class, and should be moved to Style!

---

*[src/Apps/FloatingHeads/View.elm, line 141 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7XEnTy9RzVGi1A1z:-L2z7XEnTy9RzVGi1A2-:bkpzoz0) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L141)):*
> ```Elm
>         |> Maybe.withDefault []
>         |> List.map reply
>         |> div []
> ```

I'm pretty sure this div should be an `li`

---

*[src/Apps/FloatingHeads/Menu/Actions.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z9gDFihaBr_22j65Y:-L2z9gDGfdOagDtvwosT:b-lxhb6a) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Menu/Actions.elm#L1)):*
> ```Elm
> module Apps.FloatingHeads.Menu.Actions exposing (actionHandler)
> ```

No need for Menus, I don't believe FloatingHeads will use them. Please, remove it to reduce our codebase!
(Yep, remove the Menu folder, entirely)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by PedroHLC** [comment]
**NOTE**: Do this changes in a new commit! DO NOT AMEND!

**Comment by themaxhero** [comment]
Review status: 19 of 30 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/Apps/Email/Models.elm, line 30 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1Tuz_itvvWBDD_B1:-L3-4H9WF-wXumkMlV63:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Models.elm#L30)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

No need anymore for `activeContact`, pls remove it.
Do the same to `getActiveContact` and  `setActiveContact`
</blockquote></details>

Done.

---

*[src/Apps/Email/Resources.elm, line 5 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0kSR_bit8mv0P9yk:-L3-4HfWDH0pU4IE-xEK:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Resources.elm#L5)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

There shouldn't be a need for a "Super" anymore...
</blockquote></details>

Done.

---

*[src/Apps/Email/Style.elm, line 19 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0sVDJMDkVIqCIdA2:-L3-4JJ_7Pycb5fUtoKd:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Style.elm#L19)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Move "Contacts" up, remove "Super"
</blockquote></details>

Done.

---

*[src/Apps/Email/Style.elm, line 23 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z0yblEjqJIfAvwxs7:-L3-4IseGagAvCwuxCyd:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/Style.elm#L23)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

`width (pct 100)` is `display block`(DIV's default display) default behaviour!
</blockquote></details>

Done.

---

*[src/Apps/Email/View.elm, line 48 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1p9t-PcT-C3A_JAN:-L3-4MrRZo8T8i6tb5vx:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/View.elm#L48)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

why `contactProcessor`? Why not just `contact`?
</blockquote></details>

Done.

---

*[src/Apps/Email/View.elm, line 78 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z1yfoNh3u8xE7E372:-L3-4NKo3HeAypAT2Pda:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/Email/View.elm#L78)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Why isn't this in a CSS Class (inside Style file)? If this rule is static, move it to there...
</blockquote></details>

Done.

---

*[src/Apps/FloatingHeads/Resources.elm, line 16 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z6MFAhHr-IdYDsYDZ:-L3-4NqP9v2yxmkDYtya:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Resources.elm#L16)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Were all this classes really required? why not only a Header and HeaderBtnClose?
</blockquote></details>

Done.

---

*[src/Apps/FloatingHeads/Resources.elm, line 21 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z5srPuha8ElZ_YcBI:-L3-4PNPObfISwzixpx8:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Resources.elm#L21)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Too big! This is a prefix for the classes when already on HTML side, make it smaller pls!
</blockquote></details>

Done.

---

*[src/Apps/FloatingHeads/View.elm, line 132 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7P3m9hAiJXtqTUuT:-L3-4QJ5j5FIH88lNX9Q:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L132)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Again, if this is static, then it should be a CSS Class, and should be moved to Style!
</blockquote></details>

Done.

---

*[src/Apps/FloatingHeads/View.elm, line 141 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7XEnTy9RzVGi1A1z:-L3-4Qs05rOaMbgecE9m:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L141)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

I'm pretty sure this div should be an `li`
</blockquote></details>

Done.

---

*[src/Apps/FloatingHeads/Menu/Actions.elm, line 1 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z9gDFihaBr_22j65Y:-L3-4RsnetdP4qWnRPX1:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/Menu/Actions.elm#L1)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

No need for Menus, I don't believe FloatingHeads will use them. Please, remove it to reduce our codebase!
(Yep, remove the Menu folder, entirely)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by PedroHLC** [comment]
Reviewed 11 of 17 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Apps/Email/View.elm, line 61 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L3-5dItOjlUnXnlOUH5:-L3-5dItOjlUnXnlOUH6:b-mr0fea) ([raw file](https://github.com/hackerexperience/heborn/blob/c4c3f5b3f421f5bf3c5d90d0a7dce38b0e1d7682/src/Apps/Email/View.elm#L61)):*
> ```Elm
>             case about of
>                 Just about_ ->
>                     [ src about_.picture ]
> ```

Get it out of a list

---

*[src/Apps/Email/View.elm, line 70 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L3-5hzQ-zQ2i4UIo4SV:-L3-5hzQ-zQ2i4UIo4SW:b-o64nr6) ([raw file](https://github.com/hackerexperience/heborn/blob/c4c3f5b3f421f5bf3c5d90d0a7dce38b0e1d7682/src/Apps/Email/View.elm#L70)):*
> ```Elm
> 
>         imageAttrs =
>             [ class [ Avatar ] ] ++ source
> ```

Append instead of concat

---

*[src/Apps/FloatingHeads/View.elm, line 141 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7XEnTy9RzVGi1A1z:-L3-66en45u8xIU76Wzc:bauefty) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L141)):*
<details><summary><i>Previously, themaxhero (Marcelo Amancio de Lima Santos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NOOOOOOOOOOOOOOOOOOOOOOO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368)*

**Comment by PedroHLC** [comment]
---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Apps/FloatingHeads/View.elm, line 141 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-L2z7XEnTy9RzVGi1A1z:-L3-6eJYF7ZokUqFDeM8:bvwuwr6) ([raw file](https://github.com/hackerexperience/heborn/blob/2c92143d058a175935e849fac130d848ad25fb6d/src/Apps/FloatingHeads/View.elm#L141)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

NOOOOOOOOOOOOOOOOOOOOOOO
</blockquote></details>

:looksrightthistime:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/368#-:-L3-6wju_nvftCchowFi:bvvzact)*

**Pull request merged**
