### PR TITLE
Add to LogViewer scroll and sort properly

### LINKED ISSUE #339: Funny ordering of Log messages

### PR DESCRIPTION
**Pull request by themaxhero**
Closes #339 

* Add Scroll to LogViewer app
* Fix Logs sorting to respect their timestamp

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/342)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Css/Utils.elm, line 110 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0Gew4QnlP8K4BbPesm:-L0GehOalu-2CS33pyQF:b1675zp) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/Css/Utils.elm#L110)):*
> ```Elm
> styles : List Css.Style -> Html.Attribute msg
> styles =
>     Css.asPairs >> style
> ```

Create a issue to replace `Css.asPairs >> style` usage with that.

---

*[src/Game/Servers/Logs/Models.elm, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0GfMvPbjsvT7-ykEL9:-L0GfMvPbjsvT7-ykELA:b-g618eo) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/Game/Servers/Logs/Models.elm#L111)):*
> ```Elm
>                 id
>                 model.drawOrder
>     }
> ```

```elm
let
    logs = [...]
    drawOrder = [...]
in
    [...]
```

---

*[src/Game/Servers/Logs/Models.elm, line 127 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0GfnmxTUNZPULjd3L-:-L0GfnmyvEplP4gAB_63:b36aixk) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/Game/Servers/Logs/Models.elm#L127)):*
> ```Elm
>         | logs = Dict.remove id model.logs
>         , drawOrder = searchAndDestroy 0 id model
>     }
> ```

Same as before

---

*[src/UI/Layouts/VerticalList.elm, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0Gg-69a59dsOM8YTFd:-L0Gg-69a59dsOM8YTFe:b-16p7w4) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/UI/Layouts/VerticalList.elm#L15)):*
> ```Elm
>                 |> List.singleton
>     in
>         node "verticallist" attr entries
> ```

Remove this pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342)*

**Comment by themaxhero** [comment]
*[src/UI/Layouts/VerticalList.elm, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0Gg-69a59dsOM8YTFd:-L0GkaBNfjlypLDu68aO:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/UI/Layouts/VerticalList.elm#L15)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Remove this pls
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342)*

**Comment by themaxhero** [comment]
*[src/Game/Servers/Logs/Models.elm, line 127 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0GfnmxTUNZPULjd3L-:-L0Gk_bs1uWR8VMnxLmD:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/Game/Servers/Logs/Models.elm#L127)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342)*

**Comment by themaxhero** [comment]
*[src/Game/Servers/Logs/Models.elm, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-L0GfMvPbjsvT7-ykEL9:-L0GkZe_94xEjpN0r7JV:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/d6ab271d3f3d4f38ef5f5b18e9781a0ad7061d10/src/Game/Servers/Logs/Models.elm#L111)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

```elm
let
    logs = [...]
    drawOrder = [...]
in
    [...]
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342)*

**Comment by themaxhero** [comment]
Reviewed 1 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342)*

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/342#-:-L0Gx93pXXSVWqMnVCiM:bnfp4nl)*

**Pull request merged**
