### PR TITLE
Move ContextMenu to Core and delegate it through Configs

### LINKED ISSUE #436: Fix Right Click
We need to add the menus back even for the apps that does not used it.
or when you use right click will invoke the standard context menu from the user's browser

### PR DESCRIPTION
**Pull request by PedroHLC**
Closes #436 
* Much less boilerplate
* Much more possibilities
meme embedded

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/437)

### CODE REVIEW

**Comment by kress95** [comment]
Hey, that was my hidden idea (and explicit desire: reuse apps update for menu actions

**Comment by PedroHLC** [comment]
Review status: 94 of 98 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Main.elm, line 44 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L49DlHYVa4v8BWFhf0Y:-L49v5x3uNrM1UG_oebQ:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/859a03e8ae5c4b19169c533a559d8ff260c2be97/src/Main.elm#L44)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

yeah, no one ever used time travelling...
</blockquote></details>

Done.

---

*[src/Core/Models.elm, line 36 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L49JLx-yhz8QWxJgnVJ:-L49v71ayUrn8qlmw3--:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/1fce90964842297298c8b9cd6b2ef44aaffd2a97/src/Core/Models.elm#L36)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

wtf, u mad?
</blockquote></details>

Done.

---

*[src/Core/View.elm, line 41 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L49JBJx_Ton4NPQtkXc:-L49v7xFT4DLcSO-jzIw:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/1fce90964842297298c8b9cd6b2ef44aaffd2a97/src/Core/View.elm#L41)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

get rid of this comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/437)*

**Comment by kress95** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Core/Models.elm, line 36 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L4DAlKzcBFxh4PiyhYx:-L4DAlKzcBFxh4PiyhYy:b-929tbh) ([raw file](https://github.com/hackerexperience/heborn/blob/31cfb4ec221ba23e54a7e1915e38a45a119efd90/src/Core/Models.elm#L36)):*
> ```Elm
>     , seed : Int
>     , windowLoaded : Bool
>     , contextMenu : ContextMenuMagic
> ```

I'll check if this is breaking our import/export msg history capabilities personally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/437)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Core/Messages.elm, line 29 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L4DDvOlcDpyY0VHgZZi:-L4DDvOlcDpyY0VHgZZj:b-7isox0) ([raw file](https://github.com/hackerexperience/heborn/blob/31cfb4ec221ba23e54a7e1915e38a45a119efd90/src/Core/Messages.elm#L29)):*
> ```Elm
>     | WebsocketMsg Ws.Msg
>     | LoadingEnd Int
>     | MenuMsg ContextMenuMagic
> ```

This little thingie here is breaking our msg history import/export capabilities. (master is working, the problem is Core.Msg and Core.Model)

---

*[src/Core/Models.elm, line 36 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-L4DAlKzcBFxh4PiyhYx:-L4DEAk-ZNrKy60sQsBj:b-uaprn6) ([raw file](https://github.com/hackerexperience/heborn/blob/31cfb4ec221ba23e54a7e1915e38a45a119efd90/src/Core/Models.elm#L36)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I'll check if this is breaking our import/export msg history capabilities personally.
</blockquote></details>

Yes, this guy is breaking our msg history import/export capabilities. (master is working properly)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/437)*

**Comment by kress95** [comment]
I'm accepting this for two reasons:

- (mainly because) Renato told so :stuck_out_tongue_winking_eye: 
- I created issue #440 to handle the problems this is introducing

looks ~~average~~ good to me

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/437#-:-L4DMHWf0TZbTHVc0nvk:b-6492d1)*

**Pull request merged**
