### PR TITLE
Fix Logflix scroll and sorting

### LINKED ISSUE #343: Logflix Console scroll problem
Logflix console text doesn't scroll, this issue makes it almost useless:

1. It should scroll up and down.
2. The timeline could be reversed, adding new entries to the top instead of the bottom.

### PR DESCRIPTION
**Pull request by themaxhero**
Closes #343 

* Fix Logflix scroll
* Fix Logflix and Console sorting

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/344)

### CODE REVIEW

**Comment by themaxhero** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/344)*

**Comment by kress95** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/Apps/LogFlix/View.elm, line 110 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/344#-L0HeBmOtxuugeIpzgiy:-L0HeBmOtxuugeIpzgiz:bubgjm1) ([raw file](https://github.com/hackerexperience/heborn/blob/bc96e088f81769d45ed9fda826933baeb361c860/src/Apps/LogFlix/View.elm#L110)):*
> ```Elm
>     logs
>         |> Dict.foldr (\x y acc -> acc ++ [ ( x, y ) ]) []
>         |> List.map (uncurry <| renderEntry use_string)
> ```

Bad performance, use that instead:

```
Dict.foldl (\k v acc -> renderEntry useString k v :: acc) []
```

---

*[src/OS/Console/View.elm, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/344#-L0HewcoYq8ZyyQU_z9p:-L0HewcoYq8ZyyQU_z9q:brhumzt) ([raw file](https://github.com/hackerexperience/heborn/blob/bc96e088f81769d45ed9fda826933baeb361c860/src/OS/Console/View.elm#L33)):*
> ```Elm
>         |> Dict.foldr (\x y acc -> acc ++ [ ( x, y ) ]) []
>         |> List.map (uncurry <| viewLog)
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/344)*

**Comment by kress95** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/344)*

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/344#-:-L0HgWqxcbumjwn3zv_V:bnfp4nl)*

**Pull request merged**
