### PR TITLE
Calculator

### PR DESCRIPTION
**Pull request by themaxhero**
* Added Calculator App

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/313)

### CODE REVIEW

**Comment by PedroHLC** [comment]
You made it well! Functions are very readable, as a test it is indeed perfect, keep on the good work!
:lgtm_strong: 

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[elm-package.json, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz10rJuYRwbgXfezCWP:-Kz10rJvcoeDh2311oXl:b-otdrqp) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/elm-package.json#L22)):*
> ```JSON
>         "elm-lang/html": "2.0.0 <= v < 3.0.0",
>         "elm-lang/http": "1.0.0 <= v < 2.0.0",
>         "elm-lang/keyboard": "1.0.1 <= v < 2.0.0",
> ```

WHY DO YOU LEAVE THIS HERE?

---

*[src/Apps/Calculator/View.elm, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz11mHy6q3AhVirFDke:-Kz11mHy6q3AhVirFDkf:b-yqkh1b) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L111)):*
> ```Elm
>                         Err msg ->
>                             Debug.log
>                                 "Die monster you don't belong in this world"
> ```

:robot: repeated easter egg found, use a new one instead!

---

*[src/Apps/Calculator/View.elm, line 122 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz11jwehKODvuF0sPyj:-Kz11jwehKODvuF0sPyk:bvg5g1i) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L122)):*
> ```Elm
>                         genBtn [ NormalBtn ] (Input string) string
>                 else
>                     text "Die Monster you don't belong in this world"
> ```

:robot:  Easter egg found

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-:-Kz12IAwiTf1HV1_6I9E:by7s7f2)*

**Comment by kress95** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/Calculator/View.elm, line 112 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz13Em0JKCxCQ-2vU4L:-Kz13Em0JKCxCQ-2vU4M:bgd6yrd) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L112)):*
> Debug.log

Porra Bax

---

*[src/Apps/Calculator/View.elm, line 122 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz11jwehKODvuF0sPyj:-Kz13y69u0EVyVM_mpxN:bnk8h3a) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L122)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

:robot:  Easter egg found
</blockquote></details>

:top: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/313)*

**Comment by themaxhero** [comment]
Review status: 25 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/Calculator/View.elm, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz11mHy6q3AhVirFDke:-Kz15YZ_4AEeoazmT3Y2:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L111)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

:robot: repeated easter egg found, use a new one instead!
</blockquote></details>

Done.

---

*[src/Apps/Calculator/View.elm, line 112 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/313#-Kz13Em0JKCxCQ-2vU4L:-Kz15ZCO_7ZZ7AWuB5wP:bzbkaju) ([raw file](https://github.com/hackerexperience/heborn/blob/888be3cc199726115a304983274e9c6b5e21a989/src/Apps/Calculator/View.elm#L112)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

> Debug.log

Porra Bax
</blockquote></details>

Solved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/313)*

**Comment by kress95** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/313)*

**Comment by PedroHLC** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/313)*

**Pull request merged**
