### PR TITLE
CId union refactor

### PR DESCRIPTION
**Pull request by kress95**
### DONE

Not so detailed, but works:

- [x] Change CId to Union.
- [x] Refactor Servers.Models for to use CId, remove useless bits of code.
    - [x] Cache refactor
    - [x] Decoders refactor
    - This change caused major breaks.
- [x] Create a new NIP alias, EndpointAddress.
- [x] Rename remaining bad uses of NIP (I'm looking at you @pedroHLC :joy:).
- [x] Update decoders to include Active NIP, but it's optional for now (fallbacks to internet)
- [x] Fix broken code, many problems with Processes and some views.
    - Note: there's some commented code on TaskManager.
- [x] Fix bad code and rename types to the final name presented here.
- [x] Fix Web.Update problem that caused a panic error.
    - This is what caused that dispatch.

#### I'm ready (or almost), but please do not merge me yet, I think we still need to discuss some changes I made to Account onJoin.

This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/303)

### CODE REVIEW

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/Apps/TaskManager/View.elm, line 140 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/303#-KxJOHAQQGFyKTA7z5tf:-KxJOHARiymGcp2ksrXS:b9aw3p4) ([raw file](https://github.com/hackerexperience/heborn/blob/2001f6cff0a2da62c0c675687b59403c51ddfa1d/src/Apps/TaskManager/View.elm#L140)):*
> ```Elm
>             Maybe.andThen (\a -> Maybe.map (\b -> ( a, b )) mb) ma
> 
>         {-
> ```

Ok, so remove it..

---

*[src/Decoders/Game.elm, line 132 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/303#-KxJOVu72TBT3bzS-lXn:-KxJOVu72TBT3bzS-lXo:b-vnfvlk) ([raw file](https://github.com/hackerexperience/heborn/blob/2001f6cff0a2da62c0c675687b59403c51ddfa1d/src/Decoders/Game.elm#L132)):*
> ```Elm
> 
>                     Nothing ->
>                         fail "Couldn't select an active nip for player server"
> ```

fail or panic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/303#-:-KxJPl9-hADrVtody-WU:bnfp4nl)*

**Comment by kress95** [comment]
Review status: 30 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Apps/TaskManager/View.elm, line 140 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/303#-KxJOHAQQGFyKTA7z5tf:-KxJcUp303KxCeYmaZjN:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/2001f6cff0a2da62c0c675687b59403c51ddfa1d/src/Apps/TaskManager/View.elm#L140)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Ok, so remove it..
</blockquote></details>

Done.

---

*[src/Decoders/Game.elm, line 132 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/303#-KxJOVu72TBT3bzS-lXn:-KxJcIEpDVP36ZnM6eDF:b-n53618) ([raw file](https://github.com/hackerexperience/heborn/blob/2001f6cff0a2da62c0c675687b59403c51ddfa1d/src/Decoders/Game.elm#L132)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

fail or panic?
</blockquote></details>

Check the context, this is a decoder, so fail :stuck_out_tongue:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/303)*

**Comment by kress95** [comment]
I think everything is alright now, but I'll HOLD until we get production support.

**Comment by PedroHLC** [comment]
Approved to merge by @renatomassaro , production certificate expired so it's gonna be off for a while...

**Comment by kress95** [comment]
Merging it on #306

**Pull request closed without merging**
