### PR TITLE
Dispatch Refactor 2

### PR DESCRIPTION
**Pull request by kress95**
This must be multi programmer effort, otherwise it would take too many days to finish.

We decided to do this big change because roughtly speaking... `1/3`~`1/4` of our day is wasted compiling stuff, the old dispatch was causing that, the new one here won't do it, but it's still an antipattern.

And we'll probably also deprecate this one by **gradually** migrating to configs, it won't take another monster PR like this one here, it'll take some time.

For now, this must be a multi programmer effort to work, otherwise it'll take a lot of days, task groups marked with **strong** text are parallelizable, send an PR at `kress95/HEBorn` to help me with that.

## PROGRESS

- [x] Enumerate dispatchs that should be refactored.
- [x] Add new dispatcher with compatibility layer.
- [x] Error file
- [x] Refactor dispatchable messages:
  - [x] **Core**
    - [x] Boot
    - [x] Shutdown
    - [x] Crash
    - [x] FinishSetup
  - [x] **Game**
    - [x] HandleConnected
    - [x] HandleJoinedAccount
    - [x] **Account**
      - [x] InsertGateway
      - [x] DoLogout
      - [x] DoCrash
      - [x] SetGateway
      - [x] SetEndpoint
      - [x] ContextTo
      - [x] _NotificationsMsg_
      - [x] HandleConnected
      - [x] HandleDisconnect
      - [x] Database
        - [x] HandlePasswordAcquired
    - [x] **Servers**
      - [x] SetEndpoint
      - [x] SetBounce
      - [x] HandleJoinedServer
      - [x] **Filesystem**
        - [x] Delete
        - [x] CreateTextFile
        - [x] CreateEmptyDir
        - [x] Rename
        - [x] Move
      - [x] **Logs**
        - [x] UpdateContent
        - [x] Encrypt
        - [x] Decrypt
        - [x] Hide
        - [x] Delete
      - [x] **Processes**
        - [x] Pause
        - [x] Resume
        - [x] Remove
        - [x] Complete
        - [x] StartBruteforce
        - [x] StartDownload
        - [x] StartPublicDownload
        - [x] HandleProcessStarted
        - [x] HandleProcessConclusion
        - [x] HandleBruteforceFailed
        - [x] HandleProcessesChanged
        - [x] HandleBruteforceSuccess
      - [x] _**Notifications**_
        - [x] _Insert_
        - [x] _ReadAll_
    - [x] **Storyline**
      - [x] Toggle
      - [x] Emails
        - [x] HandleNewEmail
        - [x] HandleReplyUnlocked
      - [x] Missions
        - [x] ActionDone
        - [x] HandleStepProceeded
    - [x] **Web**
      - [x] FetchUrl
      - [x] Login
      - [x] HandleJoinedServer
      - [x] HandleJoinServerFailed
  - [x] **OS**
    - [x] SessionManager
      - [x] OpenApp
      - [x] Dock
      - [x] WindowManager
    - [x] Toasts
      - [x] Append
  - [x] **Apps**
    - [x] Browser
      - [x] SomeTabMsg
      - [x] HandlePasswordAcquired
  - [x] Setup
  - [x] **Websocket**
    - [x] Broadcast
    - [x] JoinChannel
    - [x] LeaveChannel
- [x] Update tests.
- [x] Quality assertions.
- [ ] Documentation.

Tasks described with **strong** text could be done in parallel.
I'm accepting PRs at `kress95/HEBorn` to help with that.

## NOTICE

This PR depends on #303 and #294.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/306)

### CODE REVIEW

**Comment by kress95** [comment]
I'm tackling **Core** messages now.

**Comment by kress95** [comment]
I need @PedroHLC help to adapt notification dispatchs.

**Comment by PedroHLC** [comment]
Well, toasts and notifications generally are collateral effect of others dispatches, by now we kill Account/Chat/Servers notifications, and OS toasts, and let others dispatches trigger than.
The non-general cases are: User clicks "read all", and our debug toast, for those, I'm creating a top level dispatch (`Dispatch.notification`, with `Insert` and `ReadAll`) that can be reused globally...

**Comment by PedroHLC** [comment]
Approved to merge by @renatomassaro , production certificate expired so it's gonna be off for a while...

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 52 of 78 files at r1, 18 of 41 files at r2, 19 of 32 files at r3, 34 of 34 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Apps/Browser/Pages/DownloadCenter/View.elm, line 57 at r6](https://reviewable.io:443/reviews/hackerexperience/heborn/306#-KxxkoHvJkUWD8e9pAQj:-KxxkoHvJkUWD8e9pAQk:bb7r2f0) ([raw file](https://github.com/hackerexperience/heborn/blob/a7f8f00fe1675497ff0f1619b53ab25ef0d6c6c0/src/Apps/Browser/Pages/DownloadCenter/View.elm#L57)):*
> ```Elm
> view data model =
>     let
>         -- this is cheating:
> ```

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/306#-:-KxxjHUKk_bYhOfSbILT:bnfp4nl)*

**Comment by kress95** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/Apps/Browser/Pages/DownloadCenter/View.elm, line 57 at r6](https://reviewable.io:443/reviews/hackerexperience/heborn/306#-KxxkoHvJkUWD8e9pAQj:-KxxuLYOjoOb6bqR8qAi:bb8r1lk) ([raw file](https://github.com/hackerexperience/heborn/blob/a7f8f00fe1675497ff0f1619b53ab25ef0d6c6c0/src/Apps/Browser/Pages/DownloadCenter/View.elm#L57)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

why?
</blockquote></details>

I don't know anymore :joy:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/306)*

**Pull request merged**
