### PR TITLE
Implement Hacked Database

### PR DESCRIPTION
**Pull request by themaxhero**
Depends on #347
- [x] Implement HackedBankAccounts
- [x] Implement HackedBankAccounts Events
- [x] Update DBAdmin App View
- [x] Update DBAdmin App Style
- [ ] Test Events

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/351)

### CODE REVIEW

**Comment by kress95** [comment]
Rebase this baby here and I'll review it.

**Comment by kress95** [comment]
Reviewed 35 of 35 files at r1.
Review status: 6 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/Events/Account.elm, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXSe0Yjk5mOd5p5Ek:-L2MXSe13s757DUVbfxj:b-6jq633) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Events/Account.elm#L13)):*
> ```Elm
> import Events.Account.Database.DBAccountAcquired as DBAccountAcquired
> import Events.Account.Database.DBAccountUpdated as DBAccountUpdated
> import Events.Account.Database.DBAccountRemoved as DBAccountRemoved
> ```

Why DB is for Database Bank? If so,  it's already on Account.Database, so what's the point?

---

*[src/Game/Account/Database/Dummy.elm, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXrIaXF73xXZSM-mb:-L2MXrIaXF73xXZSM-mc:b-9gs270) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Database/Dummy.elm#L12)):*
> ```Elm
>         dummyServers
>         dummyAccounts
>         dummyBitcoins
> ```

Another dummy here.

---

*[src/Game/Account/Finances/Update.elm, line 54 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXyLoVCbLTPWOFqXb:-L2MXyLoVCbLTPWOFqXc:b-xor9ig) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Update.elm#L54)):*
> ```Elm
>                 |> insertBankAccount accountId bankAccount
>     in
>         Update.fromModel model_
> ```

Are these functions expected to grow?

If not, a simple `Update.fromModel <| insertBankAccount accoundId bankAccount model` would do it in a single line.

---

*[src/Game/Account/Finances/Dummy.elm, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MX7h8mtd8QifbxiQy:-L2MX7h9dipd-yM2pLDa:b-eweg06) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Dummy.elm#L11)):*
> ```Elm
>     Model
>         dummyAccounts
>         dummyBitcoins
> ```

If you're going to keep these dummies, create an issue for removing them.

---

*[src/Game/Account/Finances/Models.elm, line 60 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXFcxwhTz-AEaNC5e:-L2MXFcxwhTz-AEaNC5f:b-agdjpz) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Models.elm#L60)):*
> ```Elm
> 
> type PaymentType
>     = Purchase Shop Product Int -- Int for Product Value
> ```

Why not create a type alias for ProductValue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/351)*

**Comment by themaxhero** [comment]
Review status: 6 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/Events/Account.elm, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXSe0Yjk5mOd5p5Ek:-L2MYQ6ZLmuBCWk0Xetj:bfp9qrw) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Events/Account.elm#L13)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Why DB is for Database Bank? If so,  it's already on Account.Database, so what's the point?
</blockquote></details>

So Should i change it to AccountUpdated and AccountRemoved?

---

*[src/Game/Account/Database/Dummy.elm, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXrIaXF73xXZSM-mb:-L2MYUOEA-KXRfhbA7lR:bss4a2b) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Database/Dummy.elm#L12)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Another dummy here.
</blockquote></details>

Removed.

---

*[src/Game/Account/Finances/Models.elm, line 60 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXFcxwhTz-AEaNC5e:-L2MYiFCL8RYgNYi6jUH:bmvyhnw) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Models.elm#L60)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Why not create a type alias for ProductValue?
</blockquote></details>

Thats from finances PR, done.

---

*[src/Game/Account/Finances/Update.elm, line 54 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXyLoVCbLTPWOFqXb:-L2MZNqe2ffegXkuRuza:b6tm9gj) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Update.elm#L54)):*
> Update.fromModel <| insertBankAccount accoundId bankAccount model
Done

---

*[src/Game/Account/Finances/Dummy.elm, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MX7h8mtd8QifbxiQy:-L2MYfRL0t81FWytXsOs:bss4a2b) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Dummy.elm#L11)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

If you're going to keep these dummies, create an issue for removing them.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/351)*

**Comment by kress95** [comment]
Reviewed 12 of 13 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Events/Account.elm, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXSe0Yjk5mOd5p5Ek:-L2Ma1lCK4thNZiem7kI:b2nhtan) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Events/Account.elm#L13)):*
<details><summary><i>Previously, themaxhero wrote…</i></summary><blockquote>

So Should i change it to AccountUpdated and AccountRemoved?
</blockquote></details>

Yup

---

*[src/Game/Account/Finances/Update.elm, line 54 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXyLoVCbLTPWOFqXb:-L2Ma9QnrwpkSZVAc54E:b-uboqqg) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Game/Account/Finances/Update.elm#L54)):*
<details><summary><i>Previously, themaxhero wrote…</i></summary><blockquote>

> Update.fromModel <| insertBankAccount accoundId bankAccount model
Done
</blockquote></details>

The front pipe method was okay, the let version was the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/351)*

**Comment by themaxhero** [comment]
*[src/Events/Account.elm, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2MXSe0Yjk5mOd5p5Ek:-L2Md5A4HJi65VOngt1n:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/726f464243ba9eb45c08be8fb711ff507c296b34/src/Events/Account.elm#L13)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Yup
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/351)*

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Events/Account.elm, line 12 at r5](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-L2Mi3EidsNbegGiqCKK:-L2Mi3EjF_NVoWlhctPv:b9oecf5) ([raw file](https://github.com/hackerexperience/heborn/blob/19d8257345aa0f65640d298cc78cd17f432ae3c5/src/Events/Account.elm#L12)):*
> DBBank
DBankAccount would be better, but whatever...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/351#-:-L2MiCSk93Htz_elzInD:bnfp4nl)*

**Pull request merged**
