### PR TITLE
Virus app

### PR DESCRIPTION
**Pull request by themaxhero**
* Implement Virus App
* Implement Virus App related modals

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/454)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 34 of 46 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/Apps/VirusPanel/Update.elm, line 91 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yho1ZV0_gqQJtip6g:-L6Yho1ZV0_gqQJtip6h:b-4ptg60) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L91)):*
> ```Elm
> 
>                 _ ->
>                     { model | modal = modal }
> ```

You're always setting `modal`, why not just return the `collectSelected` and set both fields in the line bellow?

---

*[src/Apps/VirusPanel/Update.elm, line 146 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiE5CpRNy4DrMgHNQ:-L6YiE5CpRNy4DrMgHNR:bysk2n7) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L146)):*
> ```Elm
>                 { model
>                     | toCollectSelected = []
>                 }
> ```

Why use 3 lines for that? 

---

*[src/Apps/VirusPanel/Update.elm, line 228 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiNYFLjXKvnvsHR_y:-L6YiNYFLjXKvnvsHR_z:b-8ml1hy) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L228)):*
> ```Elm
>                 activeVirus =
>                     Dict.get nip (Database.getHackedServers config.database)
>                         |> Maybe.andThen (Database.getActiveVirus)
> ```

config.database
|> Database.getHackedServers 
|> Dict.get nip
|> ...

---

*[src/Apps/VirusPanel/Update.elm, line 307 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiWna3rhsCi4MFRMj:-L6YiWna3rhsCi4MFRMk:b-isv1kx) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L307)):*
> ```Elm
>                         | modal = Just <| ForCollectSuccessful
>                         , collectSelected = Nothing
>                     }
> ```

(modal, collectSelected) =

---

*[src/Apps/VirusPanel/View.elm, line 205 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YilpuCHM3y_-4Cv8s:-L6YilpuCHM3y_-4Cv8t:b2s9e7m) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/View.elm#L205)):*
> ```Elm
>                 |> flip (++) (Network.render nip)
> 
>         -- HORA DO SHOW P****
> ```

@pedrohlc 

---

*[src/Game/Account/Database/Update.elm, line 104 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YjiMwRNphWYcxV0_a:-L6YjiMwRNphWYcxV0_b:b-6vyw4b) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Game/Account/Database/Update.elm#L104)):*
> ```Elm
>                         serverNIP
>                         virusId
>                         (getHackedServers model)
> ```

can't do it in a single line? move servers to a binding

---

*[src/Game/Account/Database/Update.elm, line 126 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YjbWQZzqHEZsBufnj:-L6YjbWQZzqHEZsBufnk:b-of2cv2) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Game/Account/Database/Update.elm#L126)):*
> ```Elm
>                         | runningTime =
>                             Just config.lastTick
>                     }
> ```

caution with elm format, it will wrongly format thise things, try doing it in a single line

---

*[src/UI/Widgets/Modal.elm, line 160 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yk6Ic57TbnEu39K21:-L6Yk6Ic57TbnEu39K22:b-t0d4l5) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/UI/Widgets/Modal.elm#L160)):*
> ```Elm
>         select_ =
>             List.foldr reducer [] list
>                 |> Html.select []
> ```

try using the style 
data
|> function1
|> function2
|> function3

instead of 

function1 data
|> function2
|> function3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/454)*

**Comment by themaxhero** [comment]
Review status: 46 of 49 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/Apps/VirusPanel/Update.elm, line 91 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yho1ZV0_gqQJtip6g:-L6YoZPWl35VroToDMbD:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L91)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

You're always setting `modal`, why not just return the `collectSelected` and set both fields in the line bellow?
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/Update.elm, line 146 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiE5CpRNy4DrMgHNQ:-L6YoZ6SvAUiMHY6dYIi:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L146)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Why use 3 lines for that? 
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/Update.elm, line 228 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiNYFLjXKvnvsHR_y:-L6YoYnzOPVWeCGW4-JP:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L228)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

config.database
|> Database.getHackedServers 
|> Dict.get nip
|> ...
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/Update.elm, line 307 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YiWna3rhsCi4MFRMj:-L6YoYU0JLytbgvlB4Nw:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/Update.elm#L307)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

(modal, collectSelected) =
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/View.elm, line 205 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YilpuCHM3y_-4Cv8s:-L6YoY9YPAkpkKiIxni9:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Apps/VirusPanel/View.elm#L205)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

@pedrohlc 
</blockquote></details>

Done.

---

*[src/Game/Account/Database/Update.elm, line 104 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YjiMwRNphWYcxV0_a:-L6YoXTUdRZvuagflWGA:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Game/Account/Database/Update.elm#L104)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

can't do it in a single line? move servers to a binding
</blockquote></details>

Done.

---

*[src/Game/Account/Database/Update.elm, line 126 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YjbWQZzqHEZsBufnj:-L6YoX6tDLxkVXKh20xl:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/Game/Account/Database/Update.elm#L126)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

caution with elm format, it will wrongly format thise things, try doing it in a single line
</blockquote></details>

Done.

---

*[src/UI/Widgets/Modal.elm, line 160 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yk6Ic57TbnEu39K21:-L6YoWcMVR12eAc_dRcA:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/UI/Widgets/Modal.elm#L160)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

try using the style 
data
|> function1
|> function2
|> function3

instead of 

function1 data
|> function2
|> function3
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/454)*

**Comment by kress95** [comment]
Reviewed 1 of 3 files at r3.
Review status: 46 of 49 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/Apps/VirusPanel/Update.elm, line 84 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YotFy6K176DuX-mDS:-L6YotFy6K176DuX-mDT:byiurec) ([raw file](https://github.com/hackerexperience/heborn/blob/e901a8797e7dc44045aa0c6372d9ffa59cf97d23/src/Apps/VirusPanel/Update.elm#L84)):*
> ```Elm
>                         | modal = modal
>                         , collectSelected = collectSelected
>                     }
> ```

Too bad a single line can't handle it :/

---

*[src/Apps/VirusPanel/Update.elm, line 302 at r3](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yp4aSmfXMsSbQ1DN3:-L6Yp4aSmfXMsSbQ1DN4:b3vnqu9) ([raw file](https://github.com/hackerexperience/heborn/blob/e901a8797e7dc44045aa0c6372d9ffa59cf97d23/src/Apps/VirusPanel/Update.elm#L302)):*
> ```Elm
> 
>         model_ =
>             { model | modal = modal, collectSelected = collectSelected }
> ```

No need to put it on a model_, could Just React.update {...

---

*[src/Game/Account/Database/Update.elm, line 109 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YpTN0tOxKKQYsGazn:-L6YpTN0tOxKKQYsGazo:b36aixk) ([raw file](https://github.com/hackerexperience/heborn/blob/89976bad8a820c801fd88fedb1c057fbd4c469c8/src/Game/Account/Database/Update.elm#L109)):*
> ```Elm
>     in
>         ( model_, React.none )
> ```

Same as before

---

*[src/UI/Widgets/Modal.elm, line 160 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6Yk6Ic57TbnEu39K21:-L6YpbvpVO5zZh92yZtK:b-8nyi3w) ([raw file](https://github.com/hackerexperience/heborn/blob/118207878d0c0d43016e39de4628ade878b06bf2/src/UI/Widgets/Modal.elm#L160)):*
<details><summary><i>Previously, themaxhero (Marcelo Amancio de Lima Santos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---

*[src/UI/Widgets/Modal/Virus.elm, line 191 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-L6YpiD5XwZjlTb5qBHS:-L6YpiD5XwZjlTb5qBHT:b-ywmtmn) ([raw file](https://github.com/hackerexperience/heborn/blob/89976bad8a820c801fd88fedb1c057fbd4c469c8/src/UI/Widgets/Modal/Virus.elm#L191)):*
> ```Elm
>             |> (::) noneOption
>             |> Html.select []
> ```

Porra max

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/454)*

**Comment by kress95** [comment]
---

Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/454#-:-L6YtPF85KMNuax9UDXb:bvvzact)*

**Pull request merged**
