### PR TITLE
Better Geolocation and Leaflet ports

### PR DESCRIPTION
**Pull request by kress95**
They're waaay better than before (using a proper public API that contrasts a lot with the previous one that used `Values` everywhere).

Leaflet initialization is also improved to cover an edge case I had when testing Setup.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510)

### CODE REVIEW

**Comment by kress95** [comment]
Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---

*[src/Apps/LocationPicker/Models.elm, line 41 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4A4cNASpdI9YGyImA:-LD4A4cNASpdI9YGyImB:b-k05bce) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Apps/LocationPicker/Models.elm#L41)):*
> ```Elm
>     Cmd.batch
>         [ Leaflet.init model.mapEId
>         , getCoordinates model.self
> ```

Consistency problem

---

*[src/Setup/Pages/PickLocation/Update.elm, line 43 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4AJJB4WghVVWPxdsi:-LD4AJJDBkG6Br1RsMHT:bz0oupy) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L43)):*
> ```Elm
>         Leaflet.Clicked ({ lat, lng } as coords) ->
>             ( setCoords (Just coords) model
>             , React.cmd <| Geolocation.getLabel geoInstance lat lng
> ```

I don't like that getLabel receives lat/lng instead of a record

---

*[src/Setup/Pages/PickLocation/Update.elm, line 53 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4ANTq9xG704JV3mKe:-LD4ANTq9xG704JV3mKf:bwqgmtl) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L53)):*
> ```Elm
> onGeolocationMsg config msg model =
>     case msg of
>         Geolocation.Coordinates lat lng ->
> ```

I don't like that Geolocation.Coordinates return lat/lng instead of a record

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510)*

**Comment by PedroHLC** [comment]
There is just one thing that bothers me, why you upgraded geolocation if mapzen is being shutdown?

---

Reviewed 1 of 2 files at r1, 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Apps/LocationPicker/Models.elm, line 41 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4A4cNASpdI9YGyImA:-LD7aKUxAiDXwaZzmrR_:b-uv339h) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Apps/LocationPicker/Models.elm#L41)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Consistency problem
</blockquote></details>

Pls explain what you fully meant...

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510#-:-LD7c2ZFDnvAS2I9DqEf:bax5z9o)*

**Comment by PedroHLC** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Setup/Pages/PickLocation/Update.elm, line 43 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4AJJB4WghVVWPxdsi:-LD7cEZE4_1HxUHHLRgM:bal75a2) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L43)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I don't like that getLabel receives lat/lng instead of a record
</blockquote></details>

That's how mapzen used to work...

---

*[src/Setup/Pages/PickLocation/Update.elm, line 53 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4ANTq9xG704JV3mKe:-LD7cH_z2E6zx_PiRM7p:b-g2mwe3) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L53)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I don't like that Geolocation.Coordinates return lat/lng instead of a record
</blockquote></details>

That's just what we needed at the time, is still the only thing interesting for the backend...

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510)*

**Comment by kress95** [comment]
1. Geolocation code is not only mapzen, there's also a port of browser's geolocation
2. We'll probably switch from mapzen to something that works like it
3. Geolocation.getLabel API will probably be the same even after removing mapzen specific code
4. Mapzen-like services using the same software as mapzen are available already https://mapzen.com/blog/migration/

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Apps/LocationPicker/Models.elm, line 41 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4A4cNASpdI9YGyImA:-LD8FnwP-b_7SaDK6_ms:b-va2nuj) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Apps/LocationPicker/Models.elm#L41)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Pls explain what you fully meant...
</blockquote></details>

I'm using `Leaflet.init` there, why not use `Geolocation.getCoodinates` and minimize module context polution? (yup, I'm fixing that)

---

*[src/Setup/Pages/PickLocation/Update.elm, line 43 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4AJJB4WghVVWPxdsi:-LD8G2rLD8w86zBcwZ4W:b-4vz1nm) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L43)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

That's how mapzen used to work...
</blockquote></details>

Yes, that look'd better before finishing `Leaflet` port, now it seems weird.

---

*[src/Setup/Pages/PickLocation/Update.elm, line 53 at r2](https://reviewable.io/reviews/hackerexperience/heborn/510#-LD4ANTq9xG704JV3mKe:-LD8GRBLEFqBkk2YiH57:blkjij3) ([raw file](https://github.com/hackerexperience/heborn/blob/37f2cc86328e4273bb8b618785bf64cfdb730d90/src/Setup/Pages/PickLocation/Update.elm#L53)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

That's just what we needed at the time, is still the only thing interesting for the backend...
</blockquote></details>

I know, but you should think about  the rest of the codebase too.
These two bindings are always passed together, there's no reason for not putting them inside a tuple or record.

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510#-:-LD8EF85DytmsTlBQSvT:b3hkjug)*

**Comment by PedroHLC** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/510)*

**Pull request merged**
