### PR TITLE
Rename context to menu

### PR DESCRIPTION
**Pull request by kress95**
Depends on: Nothing, but it's better to merge other PRs first as this one will break everything

---

This one may break everything for everyone, I would recommend a synchronous merge procedure:

1. merge other PRs
2. fix conflicts for this one
3. merge this one while no complex PR is open
4. ???
5. profit

I don't know if this naming decisions is okay, and while this was great for better understanding our client side architecture, I still didn't got 100% of it and surely left some mistakes.

> As with my previous rename PRs, this one includes two commits:
>
> 1. one just renaming the files, this ensures that git recognizes the PR as a rename
> 2. other one just modifying the files...
> 
> At least to me, this helps with the merge confusions.
> The sad part is that elm is filename sensible, so the first commit is broken.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/84)

### CODE REVIEW

**Comment by kress95** [comment]
Great, but let's deffer this until other non-conflicting PRs are merged.
I'll update the PR and ask a final review from @renatomassaro.

**Comment by kress95** [comment]
Rebase still is delayed until merging anything that touches context code.

**Comment by kress95** [comment]
I'll merge this once Jenkins finish its work.

**Comment by PedroHLC** [comment]
Reviewed 74 of 74 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/84)*

**Pull request merged**
