### PR TITLE
Client addition and Setup upgrades

### PR DESCRIPTION
**Pull request by kress95**
Depends on #309

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/312)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Setup/Requests/SetServer.elm, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz1-Tcc5Tp8yoV9Z9SV:-Kz1-TcdD_gJwVfjFwwY:b-cm8nyq) ([raw file](https://github.com/hackerexperience/heborn/blob/cd99fed7ada3a5863c03514e7f2d6a0c7a39c8c0/src/Setup/Requests/SetServer.elm#L30)):*
> ```Elm
> 
> receive : List Settings -> Code -> Value -> Maybe Response
> receive settings code value =
> ```

FOUND IT

---

*[src/Setup/Requests/Setup.elm, line 37 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz1-Wu90Ri6lMKhJ_In:-Kz1-Wu90Ri6lMKhJ_Io:blml7q5) ([raw file](https://github.com/hackerexperience/heborn/blob/cd99fed7ada3a5863c03514e7f2d6a0c7a39c8c0/src/Setup/Requests/Setup.elm#L37)):*
> ```Elm
> 
>         _ ->
>             -- TODO: add better error handling
> ```

:robot: TODO task found that needs issue or to be resolved!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/312)*

**Comment by kress95** [comment]
Review status: 35 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Setup/Requests/SetServer.elm, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz1-Tcc5Tp8yoV9Z9SV:-Kz5-icgRehjWQMxgw7K:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/cd99fed7ada3a5863c03514e7f2d6a0c7a39c8c0/src/Setup/Requests/SetServer.elm#L30)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

FOUND IT
</blockquote></details>

Done.

---

*[src/Setup/Requests/Setup.elm, line 37 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz1-Wu90Ri6lMKhJ_In:-Kz5-nUZ-HhD3jYxpB83:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/cd99fed7ada3a5863c03514e7f2d6a0c7a39c8c0/src/Setup/Requests/Setup.elm#L37)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

:robot: TODO task found that needs issue or to be resolved!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/312)*

**Comment by kress95** [comment]
Review status: 35 of 37 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Setup/Update.elm, line 58 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz5GnbMYsqhLTmwXVWc:-Kz5GnbNWyEuvmu6BmgH:b-4edh6h) ([raw file](https://github.com/hackerexperience/heborn/blob/40e71aaca2732a570bc8de3ff66976f8fd629ab5/src/Setup/Update.elm#L58)):*
> ```Elm
> 
> -- message handlers
> --    Dispatch.core Core.Play
> ```

pola predo

---

*[src/Setup/Update.elm, line 72 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/312#-Kz5GqdphG5X8J7AzIKf:-Kz5GqdphG5X8J7AzIKg:b-4edh6h) ([raw file](https://github.com/hackerexperience/heborn/blob/40e71aaca2732a570bc8de3ff66976f8fd629ab5/src/Setup/Update.elm#L72)):*
> ```Elm
>                     setRequest game model
>             in
>                 ( model_, Cmd.none, Dispatch.none )
> ```

pola predo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/312)*

**Comment by PedroHLC** [comment]
Reviewed 1 of 2 files at r2, 22 of 22 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/312)*

**Pull request merged**
