### PR TITLE
Improve Request response handling

### PR DESCRIPTION
**Pull request by kress95**
Add support for checking data from websocket response headers and changes String to Value.

~~This was just recently added, so it's still not properly tested, wait for some input (from me) before merging it.~~ I tested it :smile: 

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/118)

### CODE REVIEW

**Comment by PedroHLC** [comment]
So far so good....

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/118#-:-KmaEaMH0ZJN7hJjTtNt:bkk7x5l)*

**Comment by kress95** [comment]
I'll remove the WIP tag and merge it after some testing on #121

**Comment by kress95** [comment]
Still untested :joy:

Gotta do it now with some hacks.

**Comment by kress95** [comment]
### Good news:

This PR is almost okay.

### Bad news:

The `Value -> String` method is bad and I'll have to change Requests to work with Values instead (`Value => String` turning values back to strings is costly)...

### More good news:

Fixing that is **trivial**.

### More bad news:

You will have to review it again, and it will be bigger :joy:

**Comment by PedroHLC** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/118)*

**Comment by PedroHLC** [comment]
Way better :lgtm_strong: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/118#-:-Kn5cWTOQyh6li7Z2ayQ:b-3wa4uw)*

**Pull request merged**
