### PR TITLE
Implement Database bootstrap decoding

### LINKED ISSUE #459: Remove Dummies after bootstrap been completed
* Remove Game.Account.Database.Dummy
* Remove Game.Account.Bounces.Dummy
* Remove Game.Account.Finances.Dummy

After bootstrap been completed

### PR DESCRIPTION
**Pull request by themaxhero**
Don't merge before Database's Bootstrap is on Helix's master branch
* Implement Database Decoding **100%**
Closes #459

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/473)

### CODE REVIEW

**Comment by kress95** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L7160gLeg1CibiWsfGD:bk1nuxz) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
> ```Elm
>         |> hardcoded model.notifications
>         |> hardcoded model.signOut
>         |> mainframe
> ```

delete the dummies

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by themaxhero** [comment]
*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L71FUDQ1sXMfGQfxory:bgowmdf) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

delete the dummies
</blockquote></details>

I can't delete the dummies before the bootstrap been totally completed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by PedroHLC** [comment]
Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/Apps/BounceManager/View.elm, line 220 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UFHwWWNpLcMO2idBG:-L7UFHwWWNpLcMO2idBH:b-ns3qb5) ([raw file](https://github.com/hackerexperience/heborn/blob/dcdfe82fdfff798208fed79cb820d4c9d566509e/src/Apps/BounceManager/View.elm#L220)):*
> ```Elm
> 
>             Just ForSpinner ->
>                 modalOk (Just "Think that i'm a Spinner")
> ```

"You spin me right round, baby
Right round like a record, baby
Right round round round" :musical_note: 
:laughing: 

---

*[src/Apps/VirusPanel/Update.elm, line 216 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UFpWQLIRUuDFQXfMI:-L7UFpWQLIRUuDFQXfMJ:b-tcypxv) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L216)):*
> ```Elm
>             config.activeGatewayCId
> 
>         folder k v ( acu, found ) =
> ```

```elm
folder k v acu =
  if not found && v.isActive then (k :: (Tuple.first acu), True)
  else acu
```

---

*[src/Apps/VirusPanel/Update.elm, line 230 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGEYMmqk8bWZoVdAm:-L7UGEYMmqk8bWZoVdAn:b-z66pjb) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L230)):*
> ```Elm
>                 |> Maybe.map Database.getVirusInstalled
>                 |> Maybe.map (Dict.foldr folder ( [], False ))
>                 |> Maybe.map Tuple.first
> ```

Pls, only run Map once!

---

*[src/Apps/VirusPanel/View.elm, line 222 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGVP4XxAevJiFSI7G:-L7UGVP4XxAevJiFSI7H:b-vzqkkw) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L222)):*
> ```Elm
> virusTimestamp hackedServers nip =
>     let
>         -- HORA DO SHOW P****
> ```

stop doing this! Soon our code will look like a circus!

---

*[src/Apps/VirusPanel/View.elm, line 223 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGeFbXPVoF4-9osrD:-L7UGeFbXPVoF4-9osrE:bnkg4zr) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L223)):*
> ```Elm
>     let
>         -- HORA DO SHOW P****
>         showTime str =
> ```

use pipes

---

*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L7UGjPIIrQg2i8waZWt:b-gqj7n3) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
<details><summary><i>Previously, themaxhero (Marcelo Amancio de Lima Santos) wrote…</i></summary><blockquote>

I can't delete the dummies before the bootstrap been totally completed.
</blockquote></details>

delete the dummies, use optional with initial models as fallback, keep a issue to remove it! (actually, create issues for every decoder you see hardcoded/optional)

---

*[src/Game/Account/Database/Models.elm, line 115 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UH9QApJq429EK9u7M:-L7UH9QApJq429EK9u7N:b-ku2k0w) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Game/Account/Database/Models.elm#L115)):*
> ```Elm
> getActiveVirus server =
>     server.virusInstalled
>         |> Dict.filter (\k v -> (==) True v.isActive)
> ```

```(==) True v.isActive``` equals ```v.isActive```
You can also ```\_ -> .isActive``` this would generate the nicer JS...
```


---

*[src/Game/Account/Database/Update.elm, line 128 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UHV3rCTmdmtFB9Q9I:-L7UHV3rCTmdmtFB9Q9J:b-uj0lkl) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Game/Account/Database/Update.elm#L128)):*
> ```Elm
>                         |> Maybe.map (flip (Dict.insert fileId) viruses)
>                         |> Maybe.map (\iv -> { server | virusInstalled = iv })
>                         |> Maybe.map (flip (Dict.insert nip) hackedServers)
> ```

Pls, merge maps... use a lot of ```>>```

---

*[src/UI/Style.elm, line 330 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UHc7Kc70OogndZ_OZ:-L7UHc7Kc70OogndZ_O_:b441gu) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/UI/Style.elm#L330)):*
> ```Elm
>         , border3 (px 1) solid (hex "ccc")
>         , borderTopColor (hex "07d")
>         , property "animation" "spinner .6s linear infinite"
> ```

Try to add an "animation" to Utils.Css ( :thinking:  though this name is in my PR only )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*
<!-- Sent from Reviewable.io -->

**Comment by PedroHLC** [comment]
This should be merged if Max uses "optional" in decoders!

**Comment by themaxhero** [comment]
Review status: 15 of 24 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/Apps/VirusPanel/Update.elm, line 216 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UFpWQLIRUuDFQXfMI:-L7WIKPgaiPKJxQF1QIH:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L216)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

```elm
folder k v acu =
  if not found && v.isActive then (k :: (Tuple.first acu), True)
  else acu
```
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/Update.elm, line 230 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGEYMmqk8bWZoVdAm:-L7WIL0aesqVe0JTEDfZ:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L230)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Pls, only run Map once!
</blockquote></details>

Done.

---

*[src/Apps/VirusPanel/View.elm, line 222 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGVP4XxAevJiFSI7G:-L7WAYDW6waPh9tIUR0-:bidl8dg) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L222)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

stop doing this! Soon our code will look like a circus!
</blockquote></details>

What are you talking about? It's the same comment as before moved to other function.

---

*[src/Apps/VirusPanel/View.elm, line 223 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGeFbXPVoF4-9osrD:-L7WIMm1QWIwjyiMEb8m:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L223)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

use pipes
</blockquote></details>

Done.

---

*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L7WINXVIfw7IZuRFs5z:bvcdhi2) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

delete the dummies, use optional with initial models as fallback, keep a issue to remove it! (actually, create issues for every decoder you see hardcoded/optional)
</blockquote></details>

Deleted Bounces.Dummy, Database.Dummy and Finances.Dummy

---

*[src/Game/Account/Database/Models.elm, line 115 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UH9QApJq429EK9u7M:-L7WIT3wHy7pYjUC4NOC:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Game/Account/Database/Models.elm#L115)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

```(==) True v.isActive``` equals ```v.isActive```
You can also ```\_ -> .isActive``` this would generate the nicer JS...
</blockquote></details>

Done.

---

*[src/Game/Account/Database/Update.elm, line 128 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UHV3rCTmdmtFB9Q9I:-L7WITomZuPfZrr0EC1k:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Game/Account/Database/Update.elm#L128)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Pls, merge maps... use a lot of ```>>```
</blockquote></details>

Done.

---

*[src/UI/Style.elm, line 330 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UHc7Kc70OogndZ_OZ:-L7WIVODYmj7sJBW0oMJ:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/UI/Style.elm#L330)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Try to add an "animation" to Utils.Css ( :thinking:  though this name is in my PR only )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by kress95** [comment]
Reviewed 18 of 20 files at r2, 3 of 9 files at r3.
Review status: 18 of 24 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/Apps/DBAdmin/View.elm, line 119 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7WEKqaHwDCCtJwSVie:-L7WEKqbj3Z8fLiCNk0U:bcbnxrs) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/DBAdmin/View.elm#L119)):*
> ```Elm
>                 "USD : "
>                     ++ (Maybe.withDefault "?" <| Maybe.map toMoney account.knownBalance)
>             ]
> ```

avoid writing code like that when possible:

- check the code in the left side: it was small and easy to read
- the new version is harder to read, move the complexity out to a binding

---

*[src/Apps/VirusPanel/Update.elm, line 216 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UFpWQLIRUuDFQXfMI:-L7WEgSt4A7JcQ5lRfGb:b-9398lv) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L216)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

```elm
folder k v acu =
  if not found && v.isActive then (k :: (Tuple.first acu), True)
  else acu
```
</blockquote></details>

PS: Pedro's code looks invalid, found isn't defined anywhere.

---

*[src/Apps/VirusPanel/Update.elm, line 230 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGEYMmqk8bWZoVdAm:-L7WDV8hs6QmKuWpzX1a:bape5fy) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L230)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Pls, only run Map once!
</blockquote></details>

Rewrite using the `>>` operator.

And please notice that this code is no problem for haskell, it has rewrite rules to transform

`v
|> map a
|> map b`

into

`map (a >> b) v`

Sadly, we can't rely on that when writing elm.

---

*[src/Apps/VirusPanel/View.elm, line 222 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGVP4XxAevJiFSI7G:-L7WDzEhfnl0T4bewkGX:b-cc209f) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L222)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

stop doing this! Soon our code will look like a circus!
</blockquote></details>

I think a "no repeated joke" policy is cool, repeated jokes aren't funny.

---

*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L7WFFGXSlhf7RKHelgS:bvzi0kz) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

delete the dummies, use optional with initial models as fallback, keep a issue to remove it! (actually, create issues for every decoder you see hardcoded/optional)
</blockquote></details>

Deleting any unused dummy is a **MUST**, used dummies can be kept given that they got an issue tracking them.

Also, please take pedro's comment with a grain of salt, do not use optional for fields that we don't know how to decode yet, the decode has high changes of being wrong and we would probably need to rewrite it :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by themaxhero** [comment]
*[src/Decoders/Account.elm, line 34 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7160gLeg1CibiWsfGC:-L7WL3AROlfHsg69HZNn:b-jiu4do) ([raw file](https://github.com/hackerexperience/heborn/blob/a8185045412ee43cc3de167391849e68082d7949/src/Decoders/Account.elm#L34)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Deleting any unused dummy is a **MUST**, used dummies can be kept given that they got an issue tracking them.

Also, please take pedro's comment with a grain of salt, do not use optional for fields that we don't know how to decode yet, the decode has high changes of being wrong and we would probably need to rewrite it :/

</blockquote></details>

Just Like database Decoders.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by kress95** [comment]
---

Reviewed 2 of 20 files at r2, 6 of 9 files at r3.
Review status: 19 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Apps/VirusPanel/Update.elm, line 216 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UFpWQLIRUuDFQXfMI:-L7WK5Li_6XB7OiVhiDx:bd5ogei) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/Update.elm#L216)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

PS: Pedro's code looks invalid, found isn't defined anywhere.
</blockquote></details>

PS: you noticed that

---

*[src/Apps/VirusPanel/View.elm, line 222 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGVP4XxAevJiFSI7G:-L7WKAqM5lA5-InxT3N4:bo14agy) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L222)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I think a "no repeated joke" policy is cool, repeated jokes aren't funny.
</blockquote></details>

I'm leaving my ok here

---

*[src/Apps/VirusPanel/View.elm, line 223 at r2](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7UGeFbXPVoF4-9osrD:-L7WLq778RA2XbrMWB1B:bgr5y52) ([raw file](https://github.com/hackerexperience/heborn/blob/57663fc9ffb19b896ef52cd8c07a9785b7de6573/src/Apps/VirusPanel/View.elm#L223)):*
<details><summary><i>Previously, themaxhero (Marcelo Amancio de Lima Santos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand the need to use pipes here, case seems more readable :T
In order to get any advantage of using pipes here, remove the `str` param of `showTime` and use `>>` instead of `|>`

(do that or revert to the version that uses case, it's much more readable)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-:-L7WLNtnugtz4A8pfhNV:bvvzact)*

**Comment by kress95** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Game/Account/Database/Update.elm, line 120 at r4](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-L7WMxkIcvHpnFGtZD9z:-L7WMxkIcvHpnFGtZDA-:bv9det9) ([raw file](https://github.com/hackerexperience/heborn/blob/666e9de3b92c920cf35bd1f05f7922ff194efc53/src/Game/Account/Database/Update.elm#L120)):*
> ```Elm
>                 viruses =
>                     server
>                         |> getVirusInstalled
> ```

avoid single pipes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473)*

**Comment by kress95** [comment]
---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/473#-:-L7WRG9zUdHAWozUShHE:bvvzact)*

**Pull request merged**
