### PR TITLE
More storyline

### PR DESCRIPTION
**Pull request by PedroHLC**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/503)

### CODE REVIEW

**Comment by PedroHLC** [comment]
For you to review @kress95 :see_no_evil:

**Comment by kress95** [comment]
Reviewed 7 of 8 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Game/Servers/Filesystem/Update.elm, line 52 at r2](https://reviewable.io/reviews/hackerexperience/heborn/503#-LBgm0Bd8l8qHiq2dvsU:-LBgm0Bd8l8qHiq2dvsV:b2nhqjp) ([raw file](https://github.com/hackerexperience/heborn/blob/f1963168cce4c12ec8275d81894f4394d75263d6/src/Game/Servers/Filesystem/Update.elm#L52)):*
> ```Elm
>     let
>         z =
>             Debug.log "Asking to delete file " id
> ```

WAT

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/503)*

**Comment by PedroHLC** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Game/Servers/Filesystem/Update.elm, line 52 at r2](https://reviewable.io/reviews/hackerexperience/heborn/503#-LBgm0Bd8l8qHiq2dvsU:-LBvszZ94_UkXLHFm9ZX:b-896fix) ([raw file](https://github.com/hackerexperience/heborn/blob/f1963168cce4c12ec8275d81894f4394d75263d6/src/Game/Servers/Filesystem/Update.elm#L52)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

WAT
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/503)*

**Comment by kress95** [comment]
---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/503#-:-LC0AIrhC2GzlWUzhDGi:bvvzact)*

**Pull request merged**
