### PR TITLE
Implement Requests #1 (index)

### PR DESCRIPTION
**Pull request by kress95**
### Objective

Add most of index requests, integration is lefted out for both technical (fetching server index is crashing helix) and simplicity reasons (I don't want another monster PR).

### Completion

- [x] `server.index` on **Account**
- [x] `log.index` on **Server**
- [x] `file.index` on **Server**

### DELAYED

The topics `process.index` (from _Server_) and `hack_database.index` (from _Account_) doesn't include any tests, so I'm not able to trivially figure their output formats, they are delayed until I finish adding every tested topic :stuck_out_tongue:

### NOTES

There is something wrong with `server.index`, I'm still debugging it.
Other requests aren't properly tested yet, but their decoders are **almost** compliant with the server response.

### TODOS

- [x] Test each request
- [x] Implement date decoders (or open issue on Helix for receiving unix dates instead; **EDIT:**  done)
- [x] Assert that `server.index` is working (or drop it so we can merge this first; **EDIT:** dropped for now)

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/121)

### CODE REVIEW

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/121#-:-Kn1Law-gPAvNIW-0Ziz:bnfp4nl)*

**Comment by kress95** [comment]
I'll rename this PR 'cause it won't integrate anything, it just implement requests.

**Comment by PedroHLC** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/121)*

**Comment by PedroHLC** [comment]
:lgtm: AGAIN!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/121#-:-Kn5dt81ZpDmdiNEpueF:bf6493k)*

**Pull request merged**
