### PR TITLE
Minor server refactor, also passing server to apps.

### PR DESCRIPTION
**Pull request by kress95**
Cuts some oddities from server, I strongly believe that we shouldn't do any Dict getters that doesn't add nothing to `Dict.get`.

Any non existent possibility should be threated with Maybe instead of the current weird methods (`NoLog`, `NoServer`).

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/heborn/134)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/Apps/TaskManager/Models.elm, line 112 at r1](https://reviewable.io:443/reviews/hackerexperience/heborn/134#-Knf5lCptylOeZTqfzad:-Knf5lCptylOeZTqfzae:b-4qpzso) ([raw file](https://github.com/hackerexperience/heborn/blob/de452ccd28ef7bdeb22b88b9e6949aeec88a8755/src/Apps/TaskManager/Models.elm#L112)):*
> ```Elm
>         tasks =
>             servers
>                 |> Dict.get "localhost"
> ```

:thinking:  This seems wrong!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/134)*

**Comment by kress95** [comment]
Weird, elm is reporting a dependency cycle but it runs just fine here. 🤔

**Comment by kress95** [comment]
Ffound the problem (forgot to rebase), it's alright now 😄

**Comment by PedroHLC** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/heborn/134#-:-KniKaxHIOOObnUmls3f:bnfp4nl)*

**Pull request merged**
